### ISSUE TITLE
[Bug] AVP DPF-550 disk interface causes openMSX to crash

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#968] opened 2015-07-26 00:34 UTC
Tested with openMSX-0.11.0 on Mac OS-X v10.9.5

Steps to reproduce the problem:

1) Boot a National FS-1300 with the AVP DPF-550 connected

2) Just after the disk interface beep on the MSX opening screen, openMSX will crash.

**Comment by MBilderbeek** [comment] 2015-07-26 14:35
I tried with current development version and 0.11.0 and I can't reproduce it on Linux. It just boots to basic. I also don't see any errors when I run with Valgrind.

Are you sure this isn't fixed already? see bug #957 which has been fixed in commit 93dfc19171aaad2b75092264241443afac79d6d6 on Sat Feb 21 10:06:01 2015
(This is in current development version.)

**Comment by grauw** [comment] 2015-07-26 14:35
Duplicate fixed https://github.com/openMSX/openMSX/issues/957

**Closed as completed by grauw** 2015-07-26 14:35 UTC

**Comment by sdsnatcher** [comment] 2015-07-26 17:40
> Are you sure this isn't fixed already?

Sorry, I'm still getting used with the github interface. I searched for "DPF-550" and it found nothing. It seems I have to fiddle with the search parameters.

I also don't have access to latest builds anymore, since fixato stopped publishing them for OS-X.

**Comment by MBilderbeek** [comment] 2015-07-26 17:41
Well, you could also build it yourself, it's not that hard.
