### ISSUE TITLE
kbd_mapping_mode CHARACTER has issues with US international keyboard on Windows

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1164] opened 2019-06-11 19:30 UTC
I am trying out openMSX 0.15.0 on Windows 10 1903 on a Huawei MateBook 13. Keyboard layout in Windows is set to US International.

I switched kbd_mapping_mode to CHARACTER so that the MSX should follow the keyboard layout of the laptop (and I don't have to remember where the character is on the MSX).

If I then press shift + ' (which should be ") the MSX alternates between * and "
Same thing happens with shift + 6 (which should be ^) the MSX alternates between ^ and &.

It seems to be due to 'dead key' feature on US international layout. If I switch to US layout the issue is gone in openMSX (but then typing e.g. ë becomes difficult)

**Comment by MBilderbeek** [comment] 2019-06-11 20:50
Yes, this is a known problem, see e.g. issue #947.

**Comment by MBilderbeek** [comment] 2021-04-10 20:30
Closing as duplicate of #947.

**Closed as completed by MBilderbeek** 2021-04-10 20:30 UTC
