### ISSUE TITLE
[Bug] Android: openMSX crashes on Samsung i5800 [sf#456]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#850] opened 2015-06-24 09:48 UTC
**Reported by awulms on 2012-12-16 10:29 UTC**
OpenMSX crashes on Samsung i5800. According to the debug output fro, 'adb logcat', it is in a libsdl function during the crash; See attachment for the adb logcat output

**Comment by openMSX-import** [comment] 2015-06-24 09:51
**Commented by awulms on 2012-12-16 10:29 UTC**
adb logcat output for starting openMSX on Samsun i5800
Attached file samsung_i5800_openmsx_adb_logcat_output.txt:

```
I/ActivityManager( 2003): Start proc org.openmsx.android.openmsx for activity org.openmsx.android.openmsx/.MainActivity: pid=18584 uid=10076 gids={3003, 1015} 
I/Zygote  (18584): Zygote: pid 18584 has INTERNET permission, then set capability for CAP_NET_RAW(13) 
I/WindowManager( 2003): Setting rotation to 1, animFlags=0 
I/ActivityManager( 2003): Config changed: { scale=1.0 imsi=204/16 loc=nl_NL touch=3 keys=1/1/2 nav=2/1 orien=2 layout=34 FlipFont=0} 
D/StatusBar( 2003): performAddUpdateIcon icon=IconData(slot='phone_signal' package=null iconId=10802d3 iconLevel=0) notification=null key=android.os.Binder@460ac0f8 
V/SettingsProvider( 2003): system <- value=1.0 name=font_scale 
V/SettingsProvider( 2003): property: sys.settings_system_version=313 
V/SettingsProvider( 2003): notifying: content://settings/system/font_scale 
D/StatusBar( 2003): performAddUpdateIcon icon=IconData(slot='clock' text='19:34') notification=null key=android.os.Binder@460a9238 
I/System.out(18584): libSDL: Creating startup screen 
D/dalvikvm(18584): GC freed 877 objects / 66240 bytes in 60ms 
I/System.out(18584): libSDL: onWindowFocusChanged: true - sending onPause/onResume 
W/IInputConnectionWrapper(17483): showStatusIcon on inactive InputConnection 
I/System.out(18584): libSDL: Loading libraries 
I/System.out(18584): libSDL: loaded GLESv2 lib 
I/System.out(18584): libSDL: loading lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl-1.2.so 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl-1.2.so 0x45e26958 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl-1.2.so 0x45e26958 
I/System.out(18584): libSDL: loading lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl_ttf.so 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl_ttf.so 0x45e26958 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/files/../lib/libsdl_ttf.so 0x45e26958 
D/dalvikvm(18584): No JNI_OnLoad found in /data/data/org.openmsx.android.openmsx/files/../lib/libsdl_ttf.so 0x45e26958 
I/System.out(18584): libSDL: loading lib /data/data/org.openmsx.android.openmsx/files/../lib/libxml2.so 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/files/../lib/libxml2.so 0x45e26958 
I/ActivityManager( 2003): Displayed activity org.openmsx.android.openmsx/.MainActivity: 1662 ms (total 1662 ms) 
D/StatusBar( 2003): animateCollapse(): mExpanded=false mExpandedVisible=false mAnimating=false mAnimVel=-2352.0 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/files/../lib/libxml2.so 0x45e26958 
D/dalvikvm(18584): No JNI_OnLoad found in /data/data/org.openmsx.android.openmsx/files/../lib/libxml2.so 0x45e26958 
I/System.out(18584): libSDL: loading lib /data/data/org.openmsx.android.openmsx/files/../lib/libtheora.so 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/files/../lib/libtheora.so 0x45e26958 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/files/../lib/libtheora.so 0x45e26958 
D/dalvikvm(18584): No JNI_OnLoad found in /data/data/org.openmsx.android.openmsx/files/../lib/libtheora.so 0x45e26958 
I/System.out(18584): libSDL: loading lib /data/data/org.openmsx.android.openmsx/files/../lib/libtcl8.5.so 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/files/../lib/libtcl8.5.so 0x45e26958 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/files/../lib/libtcl8.5.so 0x45e26958 
D/dalvikvm(18584): No JNI_OnLoad found in /data/data/org.openmsx.android.openmsx/files/../lib/libtcl8.5.so 0x45e26958 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeAudioInitJavaCallbacks' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeAudioInitJavaCallbacks' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeAudioInitJavaCallbacks' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libsrec_jni.so' for 'nativeAudioInitJavaCallbacks' (wrong CL) 
I/System.out(18584): libSDL: Loading settings 
I/System.out(18584): libSDL: Settings.Load(): enter 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeInitKeymap' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeInitKeymap' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeInitKeymap' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libsrec_jni.so' for 'nativeInitKeymap' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeGetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeGetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeGetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libsrec_jni.so' for 'nativeGetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeGetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeGetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeGetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libsrec_jni.so' for 'nativeGetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeGetKeymapKeyMultitouchGesture' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeGetKeymapKeyMultitouchGesture' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeGetKeymapKeyMultitouchGesture' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libsrec_jni.so' for 'nativeGetKeymapKeyMultitouchGesture' (wrong CL) 
I/System.out(18584): android.os.Build.MODEL: GT-I5800 
I/System.out(18584): libSDL: old cfg version 13040, our version 13040 
I/System.out(18584): libSDL: Settings.Load(): loaded settings successfully 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/lib/libapplication.so 0x45e26958 
W/PowerManagerService( 2003): Timer 0x3->0x3|0x0 
D/AudioHardwareALSA( 1962): codecOff 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/lib/libapplication.so 0x45e26958 
D/dalvikvm(18584): Trying to load lib /data/data/org.openmsx.android.openmsx/lib/libsdl_main.so 0x45e26958 
D/dalvikvm(18584): Added shared lib /data/data/org.openmsx.android.openmsx/lib/libsdl_main.so 0x45e26958 
D/dalvikvm(18584): No JNI_OnLoad found in /data/data/org.openmsx.android.openmsx/lib/libsdl_main.so 0x45e26958 
I/System.out(18584): libSDL: 3000-msec timeout in startup screen 
D/dalvikvm( 2003): GC freed 39057 objects / 1678456 bytes in 506ms 
I/DBG_WSS_DM( 2228): [wssTelephonyData.java Line:131] getInstance PHONE_TYPE_GSM 
D/NetworkLocationProvider( 2003): onCellLocationChanged [714,48375856] 
I/System.out(18584): libSDL: Timeout reached in startup screen, process with downloader 
I/System.out(18584): libSDL: Starting data downloader 
I/System.out(18584): libSDL: Starting downloader 
I/System.out(18584): libSDL: Initializing video and SDL application 
V/SDL     (18584): GLSurfaceView_SDL::EglHelper::start(): creating GL context 
D/dalvikvm(17483): GC freed 1265 objects / 153848 bytes in 492ms 
D/libEGL  (18584): loaded /system/lib/egl/libEGL_fimg.so 
D/libEGL  (18584): loaded /system/lib/egl/libGLESv1_CM_fimg.so 
D/libEGL  (18584): loaded /system/lib/egl/libGLESv2_fimg.so 
V/SDL     (18584): GL config 0: R5G6B5A0 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 1 
V/SDL     (18584): GL config 1: R4G4B4A4 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 9 
V/SDL     (18584): GL config 2: R5G5B5A1 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 3 
V/SDL     (18584): GL config 3: R5G6B5A0 depth 24 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 6 
V/SDL     (18584): GL config 4: R4G4B4A4 depth 24 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 14 
V/SDL     (18584): GL config 5: R5G5B5A1 depth 24 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 8 
V/SDL     (18584): GL config 6: R4G4B4A4 depth 24 stencil 8 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 13 
V/SDL     (18584): GL config 7: R5G6B5A0 depth 24 stencil 8 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 5 
V/SDL     (18584): GL config 8: R5G5B5A1 depth 24 stencil 8 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 7 
V/SDL     (18584): GL config 9: R8G8B8A8 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 17 
V/SDL     (18584): GL config 10: R8G8B8A0 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 9 
V/SDL     (18584): GL config 11: R8G8B8A8 depth 24 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 22 
V/SDL     (18584): GL config 12: R8G8B8A0 depth 24 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 14 
V/SDL     (18584): GL config 13: R8G8B8A8 depth 24 stencil 8 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 21 
V/SDL     (18584): GL config 14: R8G8B8A0 depth 24 stencil 8 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 13 
V/SDL     (18584): GLSurfaceView_SDL::EGLConfigChooser::chooseConfig(): selected 0: R5G6B5A0 depth 0 stencil 0 type 7 (GLES GLES2 OPENVG) caveat none nr 0 pos 1 
I/        (18584): libGLESv1_CM_fimg.so was loaded and GLES 1.1 API was successfully mapped 
I/        (18584):  
I/        (18584): [Chunk Allocator] 1 blocks (block size:0x200000) 
I/        (18584):  
I/        (18584):  =======Chunk::PrintChunkBlckInfo   ====== 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
I/        (18584):  [0] use flag: 1, start: 0, size: 2097152, next: 0x0 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
I/        (18584): Total Texture Size 0 Byte 0 KB Total Texture Count 0 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
V/SDL     (18584): GLSurfaceView_SDL::EglHelper::createSurface(): creating GL context 
I/System.out(18584): libSDL: DemoRenderer.onSurfaceCreated(): paused false mFirstTimeStart true 
I/System.out(18584): libSDL: DemoRenderer.onSurfaceChanged(): paused false mFirstTimeStart false 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeResize' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeResize' (wrong CL) 
I/libSDL  (18584): Physical screen resolution is 400x240, virtual screen 400x240 
D/dalvikvm(18584): GC freed 15459 objects / 372520 bytes in 62ms 
W/        (18584): error  of type 0x500  
W/        (18584): error  of type 0x500  
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeInitJavaCallbacks' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeInitJavaCallbacks' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetVideoDepth' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetVideoDepth' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetVideoLinearFilter' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetVideoLinearFilter' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetVideoForceSoftwareMode' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetVideoForceSoftwareMode' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetJoystickUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetJoystickUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetAccelerometerSettings' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetAccelerometerSettings' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetTrackballDampening' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetTrackballDampening' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetTouchscreenKeyboardUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetTouchscreenKeyboardUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetupScreenKeyboard' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetupScreenKeyboard' (wrong CL) 
D/dalvikvm(18584): GC freed 108 objects / 5584 bytes in 92ms 
D/dalvikvm(18584): GC freed 498 objects / 18760 bytes in 90ms 
I/dalvikvm-heap(18584): Grow heap (frag case) to 8.035MB for 2621456-byte allocation 
D/dalvikvm(18584): GC freed 0 objects / 0 bytes in 62ms 
D/dalvikvm(18584): GC freed 6 objects / 224 bytes in 53ms 
I/dalvikvm-heap(18584): Grow heap (frag case) to 10.290MB for 2363532-byte allocation 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetupScreenKeyboardButtons' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetupScreenKeyboardButtons' (wrong CL) 
D/dalvikvm(18584): GC freed 2 objects / 144 bytes in 131ms 
I/        (18584):  
I/        (18584): [Chunk Allocator] 2 blocks (block size:0x200000) 
I/        (18584):  
I/        (18584):  =======Chunk::PrintChunkBlckInfo   ====== 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
I/        (18584):  [0] use flag: 1, start: 0, size: 2097152, next: 0x0 
I/        (18584):  [1] use flag: 1, start: 1835040, size: 262112, next: 0x0 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
I/        (18584): Total Texture Size 1835040 Byte 0 KB Total Texture Count 8 
I/        (18584):  
I/        (18584): ------------------------------------------------------ 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetScreenKbKeyUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetScreenKbKeyUsed' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetKeymapKeyScreenKb' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetKeymapKey' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetKeymapKeyMultitouchGesture' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetKeymapKeyMultitouchGesture' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetMultitouchGestureSensitivity' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetMultitouchGestureSensitivity' (wrong CL) 
I/System.out(18584): libSDL: setting envvar LANGUAGE to 'nl_NL' 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeSetEnv' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeSetEnv' (wrong CL) 
D/SensorManager(18584): ====>>>>>Num Sensor: 1 
D/SensorManager(18584): found sensor: AK8973 Compass, handle=0 
D/SensorManager(18584): ====>>>>>Num Sensor: 2 
D/SensorManager(18584): found sensor: AK8973 Compass Raw, handle=7 
D/SensorManager(18584): ====>>>>>Num Sensor: 3 
D/SensorManager(18584): found sensor: BMA150, handle=1 
D/SensorManager(18584): ====>>>>>Num Sensor: 4 
D/SensorManager(18584): found sensor: AK8973 Temperature, handle=2 
D/SensorManager(18584): ====>>>>>Num Sensor: 5 
D/SensorManager(18584): found sensor: AK8973 Magnetic Field, handle=3 
D/SensorManager(18584): ====>>>>>Num Sensor: 0 
D/SensorManager(18584): found sensor: Proximity Sensor, handle=5 
E/SensorManager(18584): ####### akmd2 started!!! 
D/dalvikvm(18584): +++ not scanning '/system/lib/libwebcore.so' for 'nativeInit' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libmedia_jni.so' for 'nativeInit' (wrong CL) 
D/dalvikvm(18584): +++ not scanning '/system/lib/libexif.so' for 'nativeInit' (wrong CL) 
I/libSDL  (18584): Changing curdir to "/sdcard/Android/data/org.openmsx.android.openmsx/files" 
I/libSDL  (18584): Calling SDL_main("sdl") 
I/libSDL  (18584): param 0 = "sdl" 
I/openMSX (18584): Redirecting stdout to openmsx_system/openmsx.stdout and stderr to openmsx_system/openmsx.stderr 
D/openMSX (18584): MMX:  0 
D/openMSX (18584): SSE:  0 
D/openMSX (18584): SSE2: 0 
I/openMSX (18584): System data dir: /sdcard/Android/data/org.openmsx.android.openmsx/files/openmsx_system 
I/libSDL  (18584): ANDROIDAUD_OpenAudio(): app requested audio bytespersample 2 freq 44100 channels 2 samples 1024 
I/AudioPolicyManager( 1962): setOutputDevice() output 1 device 2 delayMs 0 
I/AudioPolicyManager( 1962): setOutputDevice() setting same device 2 for output 1 
I/libSDL  (18584): ANDROIDAUD_OpenAudio(): app opened audio bytespersample 2 freq 44100 channels 2 bufsize 4096 
D/AudioHardwareALSA( 1962): codecOn 
D/openMSX (18584): LocalFile: /sdcard/openMSX/share/softwaredb.xml 
I/DEBUG   (17482): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
I/DEBUG   (17482): Build fingerprint: 'samsung/GT-I5800/GT-I5800/GT-I5800:2.1-update1/ECLAIR/XWJG6:user/release-keys' 
I/DEBUG   (17482): pid: 18584, tid: 18593  >>> org.openmsx.android.openmsx <<< 
I/DEBUG   (17482): signal 4 (SIGILL), fault addr 81800000 
I/DEBUG   (17482):  r0 825fb682  r1 48a7c3d4  r2 825fb684  r3 81800000 
I/DEBUG   (17482):  r4 0028ee10  r5 81848c54  r6 825fb682  r7 82748de0 
I/DEBUG   (17482):  r8 0028ecc4  r9 826f8e9c  10 82748de0  fp 48a7c6b4 
I/DEBUG   (17482):  ip 81848da8  sp 48a7c3c8  lr 81839820  pc 81800000  cpsr a0000010 
I/AudioHardwareALSA( 1962): Initialized ALSA PLAYBACK device AndroidPlayback_Speaker_normal 
D/AudioHardwareALSA( 1962): Set PLAYBACK PCM format to S16_LE (Signed 16 bit Little Endian) 
D/AudioHardwareALSA( 1962): Using 2 channels for PLAYBACK. 
D/AudioHardwareALSA( 1962): Set PLAYBACK sample rate to 44100 HZ 
D/AudioHardwareALSA( 1962): Buffer size: 1024 
D/AudioHardwareALSA( 1962): Latency: 23219 
W/AudioFlinger( 1962): write blocked for 439 msecs, 410 delayed writes, thread 0x26138 
I/DEBUG   (17482):          #00  pc 00000000  /data/data/org.openmsx.android.openmsx/lib/libsdl-1.2.so 
I/DEBUG   (17482):          #01  pc 0003981c  /data/data/org.openmsx.android.openmsx/lib/libsdl-1.2.so 
I/DEBUG   (17482):          #02  pc 0003a3d4  /data/data/org.openmsx.android.openmsx/lib/libsdl-1.2.so 
I/DEBUG   (17482): 
I/DEBUG   (17482): code around lr: 
I/DEBUG   (17482): 81839810 0a000005 e1a00006 e28d100c ebff41c0 
I/DEBUG   (17482): 81839820 e2509000 1a000007 ea000056 e59f3178 
I/DEBUG   (17482): 81839830 e59f2178 e7953003 e7959002 e0693003 
I/DEBUG   (17482): 
I/DEBUG   (17482): stack: 
I/DEBUG   (17482):     48a7c388  00000000  
I/DEBUG   (17482):     48a7c38c  00000006  
I/DEBUG   (17482):     48a7c390  00000000  
I/DEBUG   (17482):     48a7c394  00000002  
I/DEBUG   (17482):     48a7c398  0011f250  [heap] 
I/DEBUG   (17482):     48a7c39c  a9d13f8d  /system/lib/libutils.so 
I/DEBUG   (17482):     48a7c3a0  00145938  [heap] 
I/DEBUG   (17482):     48a7c3a4  0011f250  [heap] 
I/DEBUG   (17482):     48a7c3a8  00000006  
I/DEBUG   (17482):     48a7c3ac  a9d140a5  /system/lib/libutils.so 
I/DEBUG   (17482):     48a7c3b0  001458e8  [heap] 
I/DEBUG   (17482):     48a7c3b4  34a7c3dc  
I/DEBUG   (17482):     48a7c3b8  36393034  
I/DEBUG   (17482):     48a7c3bc  62794828  
I/DEBUG   (17482):     48a7c3c0  df002777  
I/DEBUG   (17482):     48a7c3c4  e3a070ad  
I/DEBUG   (17482): #01 48a7c3c8  00000208  
I/DEBUG   (17482):     48a7c3cc  00000004  
I/DEBUG   (17482):     48a7c3d0  8183b4f4  /data/data/org.openmsx.android.openmsx/lib/libsdl-1.2.so 
I/DEBUG   (17482):     48a7c3d4  afe174cb  /system/lib/libc.so 
I/DEBUG   (17482):     48a7c3d8  001551e4  [heap] 
I/DEBUG   (17482):     48a7c3dc  48a7c65c  
I/DEBUG   (17482):     48a7c3e0  0028ee10  [heap] 
I/DEBUG   (17482):     48a7c3e4  48a7c400  
I/DEBUG   (17482):     48a7c3e8  82748de0  
I/DEBUG   (17482):     48a7c3ec  0028ecc4  [heap] 
I/DEBUG   (17482):     48a7c3f0  826f8e9c  /data/data/org.openmsx.android.openmsx/lib/libapplication.so 
I/DEBUG   (17482):     48a7c3f4  82748de0  
I/DEBUG   (17482):     48a7c3f8  48a7c6b4  
I/DEBUG   (17482):     48a7c3fc  8183a3d8  /data/data/org.openmsx.android.openmsx/lib/libsdl-1.2.so 
D/Zygote  ( 1961): Process 18584 terminated by signal (4) 
I/AudioPolicyManager( 1962): setOutputDevice() output 1 device 0 delayMs 48 
I/WindowManager( 2003): WIN DEATH: Window{4609b600 SurfaceView paused=false} 
I/ActivityManager( 2003): Process org.openmsx.android.openmsx (pid 18584) has died. 
I/WindowManager( 2003): WIN DEATH: Window{46527728 org.openmsx.android.openmsx/org.openmsx.android.openmsx.MainActivity paused=false} 
I/WindowManager( 2003): Setting rotation to 0, animFlags=0 
I/ActivityManager( 2003): Config changed: { scale=1.0 imsi=204/16 loc=nl_NL touch=3 keys=1/1/2 nav=2/1 orien=1 layout=34 FlipFont=0} 
I/UsageStats( 2003): Unexpected resume of com.sec.android.app.twlauncher while already resumed in org.openmsx.android.openmsx 
I/DBG_WSS_DM( 2228): [wssTelephonyData.java Line:131] getInstance PHONE_TYPE_GSM 
D/Launcher(17483): launcher is resumed 
D/NetworkLocationProvider( 2003): onCellLocationChanged [714,48375857] 
V/SettingsProvider( 2003): system <- value=1.0 name=font_scale 
V/SettingsProvider( 2003): property: sys.settings_system_version=314 
V/SettingsProvider( 2003): notifying: content://settings/system/font_scale 
V/SettingsProvider( 2003): system <- value=1 name=mtp_usb_connection_status 
V/SettingsProvider( 2003): property: sys.settings_system_version=315 
V/SettingsProvider( 2003): notifying: content://settings/system/mtp_usb_connection_status 
W/InputManagerService( 2003): Got RemoteException sending setActive(false) notification to pid 18584 uid 10076 
D/StatusBar( 2003): performAddUpdateIcon icon=IconData(slot='clock' text='19:34') notification=null key=android.os.Binder@460a9238 
D/dalvikvm( 2003): GC freed 9420 objects / 501376 bytes in 493ms 
D/AudioHardwareALSA( 1962): codecOff 
```

**Comment by MBilderbeek** [comment] 2016-08-04 19:20
I propose to report this to the commandergenius developer. Nothing we can do about it...

**Comment by mthuurne** [comment] 2016-08-05 08:11
SDL is open source; we can do something about it if we want to ;)

I think it would be useful to investigate a bit more before sending this upstream. Something weird is going on here: SIGILL means an illegal instruction was encountered. Usually that either means that code was compiled with instructions not available on the CPU running the code, or that something that is not code was jumped to.

Is it possible to get a stack trace from a build with debug symbols in it? Because it would help a lot if we'd know through which functions this crash was triggered.

**Comment by mthuurne** [comment] 2016-08-05 08:13
I see now that this is an imported bug originally filed in 2012. It would be useful to re-test with the latest openMSX. Or if the device is no longer available to test on, close the bug.

**Comment by MBilderbeek** [comment] 2016-12-18 20:41
Alex, agreed to close this? Or can it still be reproduced?

**Comment by MBilderbeek** [comment] 2018-08-21 21:11
Let's just close it.

**Closed as completed by MBilderbeek** 2018-08-21 21:11 UTC
