### ISSUE TITLE
save_msx_screen issues

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1097] opened 2018-01-12 23:50 UTC
Tested on openMSX-0.14.0-gf02f3ce, on Mac OS-X.

==First issue==

When you try to use the save_msx_screen to save the intro screen of the MSXdev07 game Lotus F3, it saves bogus information for the sprites.

Steps to reproduce:

1) Boot openMSX with the LOTUSF3.ROM on your preferred MSX machine
2) On the intro screen, open the console and type: save_msx_screen LOTUSF3
3) Quit openMSX, and boot it again without any cartridges and with the LOTUSF3.SC2 file on drive A:
4) Run the following program:

10 SCREEN2,2
20 BLOAD"LOTUSF3.SC2",S
30 GOTO 30

6) The screen will show bogus sprites as in the attached screenshot

![lotusf3_bogussprites](https://user-images.githubusercontent.com/13080763/34899663-68277402-f7e1-11e7-8207-33a814d941f8.png)

==Second Issue==

When you try to use save_msx_screen to save the contents of the VRAM while playing Zone Terra, the background gets some weird repeated blocks.

Steps to reproduce:

1) Boot openMSX an MSX Turbo-R with Zone Terra on drive A:
2) Start the game.
3) When the stage-1 is playing, open the console and break the emulation
4) type on console: debug set_bp 0x38
5) Connect the openMSX debugger
6) Open the VDP register window
7) Run the emulation again, and it will break at 0x38. Repeat this until the VDP register window tells you that the VDP is set to screen-12
8) Type save_msx_screen ZTERRA1 on the console
9) Swap the disk on drive A: with a directory containing the ZT-STG1 file and reboot the MSXTR
10) Run the following BASIC program:

10 SCREEN12,2
20 BLOAD"ZTERRA1.SCC",S
30 GOTO 30

The screen will show some weird repeated blocks on the background, and the background will not be at the same position as it was in the game.

**Comment by mthuurne** [comment] 2018-01-13 00:02
I'm not sure if this is the cause, but saving the screen data will not work for games that do raster tricks. For example Space Manbow switches between different sprite tables during the scanline conversion of the display area, so a capture of the sprite tables at any given time is never going to be complete.

As for the background not being at the same position, that can be explained by the hardware scroll, which doesn't scroll the VRAM (that would be too slow), but instead changes the line where the VDP starts displaying the VRAM.

So the problems you're seeing might be a result of limitations of what the script can do rather than bugs.

**Comment by sdsnatcher** [comment] 2018-01-13 00:07
Humm. But:

- Space Manbow dumps seem come out fine
- The script already takes the vertical scroll into account. Aleste-1 and Aleste-2 dumps come out fine
- I changed the CPU speed in Lotus F3 to check if it uses raster tricks on the MSX1, and there where no collateral effects in the screen. It doesn't seem to use raster tricks to me.

**Comment by sdsnatcher** [comment] 2018-03-20 19:22
One additional issue with the save_msx_screen script:

- It doesn't support interlaced images. They could be saved as a pair of image files, just like expected by the Japanese image viewers like BLS.COM and BL.COM:  .sc5+.s15, .sc6+.s16, .sc7+.s17, .sc8+.s18,  .sca+.s1a, .scc+.s1c

**Comment by NYYR1KK1** [comment] 2018-06-17 12:05
About the first issue... Your line 10 is wrong... It should be 10 SCREEN 2,0 (Sprite size / zoom / visibility information can't be stored in to the file)

About 2nd issue... Programs that use CPU to alter image outlook in real time (screen splits, palette changes etc) are out of scope. These kind of images can't be stored with this script. *.SCx files don't contain any information about how the pictures should be displayed, so this script can't be used to store this kind of information in future either.

**Comment by sdsnatcher** [comment] 2018-10-06 14:18
You nailed the Lotus F3 problem, NYYR1KK1. Indeed this game is one of the very few that uses 8x8 sprites. It's so rare that I overlooked it.

About 2nd issue: Yes, I understand that raster tricks cannot be saved this way. But interlaced images (aka 424i) are not raster tricks, and can be easily detected/dumped by looking at the mode registers, just like normal progressive images.

**Comment by MBilderbeek** [comment] 2019-10-27 22:35
looks like @sdsnatcher implemented the interlaced stuff, see https://www.msx.org/forum/msx-talk/general-discussion/taking-sc5-snapshot-games?page=4

Can someone review this?

Pasting:
```
set_help_text save_msx_screen \
{Lookup the screen mode and save the current screen to a MSX compatible binary
file. This file can for example be loaded in MSX-BASIC using the BLOAD command.

This script was originally developed by NYYRIKKI, see also this forum thread:
  <a href="http://www.msx.org/forum/msx-talk/general-discussion/taking-sc5-snapshot-games" title="http://www.msx.org/forum/msx-talk/general-discussion/taking-sc5-snapshot-games">http://www.msx.org/forum/msx-talk/general-discussion/taking-...</a>
}

proc save_msx_screen {basename} {
	set directory [file normalize $::env(OPENMSX_USER_DATA)/../screenshots]
	# Create filename with correct extension (also gives an error in
	# case of an invalid screen mode).
	set fname [file join $directory [format "%s.SC%X" $basename [get_screen_mode_number]]]
	set fname2 [file join $directory [format "%s.S1%X" $basename [get_screen_mode_number]]]

	set name_base        [expr { [vdpreg 2]        * 0x400}]
	set name_base_80     [expr {([vdpreg 2] & 252) * 0x400}]
	set name_base_bitmap [expr {([vdpreg 2] &  96) * 0x400}]
	set color_base       [expr { [vdpreg 3]        * 0x40 + [vdpreg 10] * 0x4000}]
	set color_base_2     [expr {([vdpreg 3] & 128) * 0x40 + [vdpreg 10] * 0x4000}]
	set pattern_base     [expr { [vdpreg 4]        * 0x800}]
	set pattern_base_2   [expr {([vdpreg 4] & 60)  * 0x800}]
	set spr_att_base     [expr { [vdpreg 5]        * 0x80 + [vdpreg 11] * 0x8000}]
	set spr_att_base_2   [expr {([vdpreg 5] & 252) * 0x80 + [vdpreg 11] * 0x8000 - 0x200}]
	set spr_pat_base     [expr { [vdpreg 6]        * 0x800}]
	set interlace        [expr {([vdpreg 9] >> 2 ) & ([vdpreg 9] >> 3 ) & [expr {[vdpreg 2] >> [expr {[get_screen_mode] < 7 ? 4:5}]}] & 1 }]

	switch [get_screen_mode] {
	"TEXT40" {
		lappend sections "VRAM" $name_base 0x400                    ;# BG Map
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$name_base + 0x420}] 0x3E0   ;# Fill (BG Map)
		lappend sections "VRAM" $pattern_base 0x800                 ;# BG Tiles
	}
	"TEXT80" {
		lappend sections "VRAM" $name_base_80 0x800                 ;# BG Map
		lappend sections "VRAM" $color_base 0x700                   ;# Blink
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$name_base_80 + 0xF20}] 0xE0 ;# Fill (BG Map)
		lappend sections "VRAM" $pattern_base 0x800                 ;# BG Tiles
	}
	"1" {
		lappend sections "VRAM" $pattern_base 0x1800                ;# BG Tiles
		lappend sections "VRAM" $name_base 0x300                    ;# BG Map
		lappend sections "VRAM" $spr_att_base 0x500                 ;# OBJ Attributes
		lappend sections "VRAM" $color_base 0x20                    ;# BG Colors
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$color_base + 0x40}] 0x17C0  ;# Fill (BG Colors)
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# OBJ Tiles
	}
	"2" {
		lappend sections "VRAM" $pattern_base_2 0x1800              ;# BG Tiles
		lappend sections "VRAM" $name_base 0x300                    ;# BG Map
		lappend sections "VRAM" $spr_att_base 0x80                  ;# OBJ Attributes
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$spr_att_base + 0xA0}] 0x460 ;# Fill (OBJ Attributes)
		lappend sections "VRAM" $color_base_2 0x1800                ;# BG Colors
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# OBJ Tiles
	}
	"3" {
		lappend sections "VRAM" $pattern_base 0x800                 ;# BG Tiles
		lappend sections "VRAM" $name_base 0x1300                   ;# BG Map
		lappend sections "VRAM" $spr_att_base 0x520                 ;# OBJ Attributes
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$spr_att_base + 0x540}] 0x17C0 ;# Fill (OBJ Attributes)
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# OBJ Tiles
	}
	"4" {
		lappend sections "VRAM" $pattern_base_2 0x1800              ;# BG Tiles
		lappend sections "VRAM" $name_base 0x380                    ;# BG Map
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$name_base + 0x3A0}] 0x60    ;# Fill (BG Map)
		lappend sections "VRAM" $spr_att_base_2 0x400               ;# OBJ Attributes
		lappend sections "VRAM" $color_base_2 0x1800                ;# BG Colors
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# OBJ Tiles
	}
	"5" - "6" {
		set lines1 [expr {[vdpreg 23] > 24 ? 256 - [vdpreg 23] : 232}] ;# Store 232 lines, even
		set lines2 [expr {232 - $lines1}]                              ;# though only 212 are visible
		set base1 [expr {$name_base_bitmap -(0x8000 * $interlace) + [vdpreg 23] * 128}]
		set base2 [expr {$name_base_bitmap -(0x8000 * $interlace)}]
		lappend sections "VRAM" $base1 [expr {$lines1 * 128}]       ;# Bitmap (part 1)
		lappend sections "VRAM" $base2 [expr {$lines2 * 128}]       ;# Bitmap (part 2)
		lappend sections "VRAM" $spr_att_base_2 0x280               ;# Sprite colors + attributes
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		lappend sections "VRAM" [expr {$name_base_bitmap -(0x8000 * $interlace) + 0x76A0}] 0x160 ;# Fill (Bitmap)
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# Sprite character patterns
		if { $interlace == 1 } {
			lappend sections2 "VRAM" [expr {$base1 + 0x8000}] [expr {$lines1 * 128}]	;# Bitmap (part 1)
			lappend sections2 "VRAM" [expr {$base2 + 0x8000}] [expr {$lines2 * 128}]	;# Bitmap (part 2)
			lappend sections2 "VRAM" [expr {$spr_att_base_2 + 0x8000}] 0x280		;# Sprite colors + attributes
			lappend sections2 "VDP palette" 0 0x20						;# Palette
			lappend sections2 "VRAM" [expr {$name_base_bitmap + 0x76A0}] 0x160		;# Fill (Bitmap)
			lappend sections2 "VRAM" [expr {$spr_pat_base + 0x8000}] 0x800			;# Sprite character patterns
		}
	}
	"7" - "8" - "11" - "12" {
		set lines1 [expr {[vdpreg 23] > 16 ? 256 - [vdpreg 23] : 240}] ;# Store 240 lines, even
		set lines2 [expr {240 - $lines1}]                              ;# though only 212 are visible
		set base1 [expr {($name_base_bitmap * 2) & 0x10000 - (0x10000 * $interlace) + [vdpreg 23] * 256}]
		set base2 [expr {($name_base_bitmap * 2) & 0x10000 - (0x10000 * $interlace) }]
		lappend sections "VRAM" $base1 [expr {$lines1 * 256}]       ;# Bitmap (part 1)
		lappend sections "VRAM" $base2 [expr {$lines2 * 256}]       ;# Bitmap (part 2)
		lappend sections "VRAM" $spr_pat_base 0x800                 ;# Sprite character patterns
		lappend sections "VRAM" $spr_att_base_2 0x280               ;# Sprite colors + attributes
		lappend sections "VDP palette" 0 0x20                       ;# Palette
		if { $interlace == 1 } {
			lappend sections2 "VRAM" [expr {$base1 + 0x10000}] [expr {$lines1 * 256}]	;# Bitmap (part 1)
			lappend sections2 "VRAM" [expr {$base2 + 0x10000}] [expr {$lines2 * 256}]	;# Bitmap (part 2)
			lappend sections2 "VRAM" [expr {$spr_pat_base + 0x10000}] 0x800			;# Sprite character patterns
			lappend sections2 "VRAM" [expr {$spr_att_base_2 + 0x10000}] 0x280		;# Sprite colors + attributes
			lappend sections2 "VDP palette" 0 0x20			;# Palette
		}
	}}

	# open file
	set out [open $fname w]
	fconfigure $out -translation binary

	# write header
	set end_addr -1
	foreach {type addr size} $sections {
		incr end_addr $size
	}
	set header [ 0xFE 0 0 [expr {$end_addr & 255}] [expr {$end_addr / 256}] 0 0]
	puts -nonewline $out [binary format c* $header]

	# write data sections
	foreach {type addr size} $sections {
		puts -nonewline $out [debug read_block $type $addr $size]
	}
	close $out

	if { $interlace == 1 } {		# Write the 2nd part of an interlaced image
		# open file
		set out [open $fname2 w]
		fconfigure $out -translation binary
	
		# write header
		set end_addr -1
		foreach {type addr size} $sections2 {
			incr end_addr $size
		}
		puts -nonewline $out [binary format c* $header]
	
		# write data sections
		foreach {type addr size} $sections2 {
			puts -nonewline $out [debug read_block $type $addr $size]
		}
		close $out
	}

	return [expr { $interlace==0 ? "Screen written to $fname":"Screen written to $fname + $fname2" }]
}
```

**Comment by MBilderbeek** [comment] 2019-10-27 22:38
Now attached as patch.
[interlace.patch.txt](https://github.com/openMSX/openMSX/files/3776513/interlace.patch.txt)

**Comment by NYYR1KK1** [comment] 2019-10-27 23:08
I have not tried it, but judging from sources it seems ok to my eyes from functionality point of view. I think it could be size optimized by making fname as a list and using foreach for writing or maybe by making file write as function, but as this kind of stuff does not really affect functionality in the end, this is more like useless nitpicking. It anyway seems like a good improvement.

**Comment by m9710797** [comment] 2019-10-28 16:55
Done.
In a 1st step I've imported the script (unchanged), and in a 2nd step made some tweaks.

**Closed as completed by m9710797** 2019-10-28 16:55 UTC
