### ISSUE TITLE
[Bug] Reverse bar fadeout fails in some particular case [sf#529]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#921] opened 2015-06-24 11:46 UTC
**Reported by manuelbi on 2014-04-27 19:15 UTC**
When the reverse bar is 'at the end', but not yet faded away. And you exit the openmsx window with the mouse at the bottom. The reverse bar won't automatically fade away. the reason is that SDL seems to clip the mouse coordinates at the window border. So according to the reverse bar script, the mouse is still above the reverse bar.

Is there something easy we can do about this?

**Comment by MBilderbeek** [comment] 2016-02-29 22:07
I can't reproduce this anymore today.... so let's just close it.

**Closed as completed by MBilderbeek** 2016-02-29 22:07 UTC
Labels: reverse
