### ISSUE TITLE
Wrong characters mapped to key presses in international keyboard

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1610] opened 2024-04-11 13:52 UTC
Using international keyboard with dead keys on Fedora Linux and `-machine MSX2`, when I press shift+6 (keycap "6^") I get `&` first (which is unexpected) and then `^` the second time. It alternates between `&` and `^` while I continue pressing it.

**Comment by MBilderbeek** [comment] 2024-04-11 15:59
Duplicate of #1441.

**Closed as completed** 2024-04-11 16:00 UTC
