### ISSUE TITLE
Fullscreen on Mac OS X shows garbled images around the display field

### ISSUE THREAD

**Issue by lavadrop** [openMSX/openMSX#1028] opened 2016-06-20 07:02 UTC
The fullscreen option shows corrupted image data that flickers.
When the renderer uses the CRT-like geometry shader, fullscreen displays correctly.

![1](https://cloud.githubusercontent.com/assets/6760790/16185582/832de228-368a-11e6-98aa-93c621dd5d53.jpg)

Mac OS 10.11.5
Neko Launcher 15
OpenMSX 0.12.0

SDLGL-PP: Normal
Simple scaler
Scanlines 20
Blur 50
Glow 0
Noise 0
Gamma 1.10

**Comment by MBilderbeek** [comment] 2016-06-28 19:53
Fullscreen is implemented by openMSX by simply giving a flag to the SDL library. In other words: there's not much openMSX specific code for full screen. Rendering glitches in full screen are therefore most likely caused by the SDL library, of which we use the 1.2 version, which is no longer maintained. We should move off of SDL 1.2, but it's not that easy... 

So, this is not something we can easily fix. Actually problems like these have been reported before. See e.g. #532 . Which scale factor setting are you using anyway? (Don't know if it's relevant, though...)

**Comment by lavadrop** [comment] 2016-06-28 21:50
All scalers are affected

**Comment by MBilderbeek** [comment] 2016-06-29 18:39
Can you be a bit clearer on this: "When the renderer uses the CRT-like geometry shader, fullscreen displays correctly."
Which exact openMSX settings influence the wrong display?

**Comment by lavadrop** [comment] 2016-06-29 18:43
NekoLauncher has a renderer called SDLGL-PP 3D. This applies what I assume is a shader with geometry modifications and scanlines. When choosing this renderer, the artifacts no longer appear.

**Comment by MBilderbeek** [comment] 2016-06-29 18:47
Aha, well, I recommend to use SDLGL-PP anyway, as it saves you a lot of CPU time for the graphics rendering. The 'normal' SDL renderer will disappear in the future.

FYI, SDLGL-PP is an OpenGL 2 based renderer, that indeed uses shaders. It doesn't imply scanlines, that depends on the scale_algorithm setting. See also http://openmsx.org/manual/user.html#renderers

**Comment by MBilderbeek** [comment] 2018-10-06 19:28
FRS wrote on MRC:

> Well, I found a workaround that avoids the glitch. If, before going fullscreen, the scale_factor is set to 2, then set back to 3 (or 4) only after the fullscreen is set, the glitch doesn't happen.
>
> Maybe this workaround could be implemented on openMSX until the move to SDL-2 finally happens? 

Could be a useful idea.

**Comment by MBilderbeek** [comment] 2019-03-09 21:05
@lavadrop @sdsnatcher Please try full screen with the latest development version (3f390b404486f3c082a83914f29e294dc1308fb4 or later).
It should work much better now.

**Comment by lavadrop** [comment] 2019-03-16 21:12
Thank you. I no longer have a Mac to test your fix, though.

**Comment by MBilderbeek** [comment] 2019-03-16 22:27
@lavadrop Thanks for letting us know. I'll rely on @sdsnatcher then...

**Comment by sdsnatcher** [comment] 2019-03-31 15:40
I just tested with openmsx-0.15.0-270-gbec899df5-mac-x86_64-bin.dmg. The garbage around the display seems to have been solved, and the scaler code also seems way better: the MSX screen size now remains the same regardless of the scale_factor being used.

But another bug seems to have surfaced: if I go fullscreen, then go back to the windowed mode, the mouse will stay grabbed and I cannot do anything with the mouse pointer outside the openMSX window.

Curiously enough, not even the MSX mouse pointer will move when this happen. An invisible mouse pointer seems to be only able to click on the openMSX ovelay interface, opening menus and things like this.

I checked the grab_input state on the openMSX terminal and it's false.

**Comment by MBilderbeek** [comment] 2019-03-31 18:19
@niekvlessert Can you reproduce what @sdsnatcher is reporting?

**Comment by niekvlessert** [comment] 2019-03-31 19:52
Yes, I can! Tested using 0.15.0-261. I can get out of the behaviour by using cmd-tab to another window, and it happens again when switching back to OpenMSX.

It happens in both sdl and sdlgl-pp.

**Comment by MBilderbeek** [comment] 2019-03-31 21:47
Could be that the workaround I created for #764 is now getting in the way... @niekvlessert confirmed it works again when reverting 4d3d400c6411d3c4cce30ebcb063e47a25c9d493
@sdsnatcher Please try the next autobuilt binary to confirm... and also please recheck #764 .

**Comment by MBilderbeek** [comment] 2020-05-30 22:17
@sdsnatcher @niekvlessert  Can you check whether this issue is still actual?

**Comment by MBilderbeek** [comment] 2020-11-22 22:30
@niekvlessert @sdsnatcher ping?

**Comment by MBilderbeek** [comment] 2021-04-10 20:51
@niekvlessert @sdsnatcher Last call.... :P

**Comment by niekvlessert** [comment] 2021-04-10 21:06
Sorry for the late reply, no issues here anymore.

**Comment by MBilderbeek** [comment] 2021-04-10 21:08
OK, closing then. Thanks!

**Closed as completed by MBilderbeek** 2021-04-10 21:08 UTC
