### ISSUE TITLE
recently executed instructions incorrectly disassembled

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1626] opened 2024-05-20 18:33 UTC
Hi,

during step-by-step execution, some instructions look scrambled on the Disassembly windows right after they are executed.

See this video:

https://youtu.be/7RI1qByONKo

**Comment by m9710797** [comment] 2024-05-21 08:08
It wasn't clear in the video, but i think you use the step-over function on a CALL instruction, right?

I tried to reproduce the problem but I didn't succeed. I suspect it only triggers in (very?) specific situations. And then in particular with very specific memory content. Could you send a memory dump? Only the memory "around" the current PC should be sufficient (and the stuff in front is more important). E.g. could you send a memory dump of addresses 0x0000-0x0400? You could use the `save_debuggable` console command for this (type `help save_debuggable` for more info).

Some background info:
In general it's not possible to always show a "correct" disassembly view. This is because Z80 instructions are variable length. So a byte sequence like `CD 11 22` could either be disassembled as a single `CALL 0x2211` instruction or it could be that the `CD` byte is part of the previous instruction and a new `LD DE,<nn>` instruction starts at the `11` byte.

Because in general it's not possible to always show the correct disassembly we use an heuristic:
* We show the disassembly as-if you would start disassembling from address 0x0000.
* The only exception is: if the PC falls in the "middle" of an instruction, we don't fully disassemble that instruction. Instead we show the proceeding bytes as `db xx, yy` and then start disassembling a new instruction at the location of the PC.

It's this second rule that kicks-in in your video. But it's not clear to me yet whether this is the intended behavior (at least according to the above heuristic) or if maybe we made a bug while implementing these heuristics. And to be able to investigate this it would be very useful to have a memory dump (of all bytes that come before the PC).

And if the behavior is correct according to the heuristics, then we should think about how to tweak the heuristics. Because I agree, the behavior in the video is weird.

**Comment by Colpocorto** [comment] 2024-05-21 11:23
If I've just executed an instruction that was being correctly shown just one step before, it should be just scrolled up. Any other behaviour would be wrong by design, IMHO.

Furthermore, it doesn't happen with the classic debugger.

I'll try to prepare a dump later on reproducing the issue.

**Comment by m9710797** [comment] 2024-05-21 16:08
I took a more detailed look at the video you made. It does already contain enough context information (no need anymore for a memory dump).

I think I now also understand what's going on.
* Right before you execute the step-over command, the memory at location 0x17C contains these 4 bytes: `00 FF 00 FF`.
* After this call returns that memory has been changed to `83 03 84 01`.
* That last byte `0x01` is the opcode for the `ld bc,<nn>` instruction which is a 3-byte instruction.
* This change (`FF` -> `01`, a 1-byte to a 3-byte instruction) has an influence on how the following instructions are disassembled. And in this specific example this change is located _very_ close to the instructions that are being executed.

So, I fully agree this is unexpected, and undesired. But it really is the expected behavior for the current implementation (with the current heuristics).

I also wouldn't know how to improve the heuristics (and not make it super complicated). To solve this you'd have to know which parts of the memory contain instructions and which contain data. (And then also consider cases like self-modifying code, or a decompression routine which produces data which then later turns out to be executable code, etc).

I'm closing this ticket. But feel free to re-open if you don't agree with my analysis. Or if you have a suggestion for how to improve the heuristics.

**Closed as completed by m9710797** 2024-05-21 16:08 UTC
Labels: Debugger, imgui

**Comment by Colpocorto** [comment] 2024-05-21 17:31
Maybe you don't need heuristics here. Just scroll up the code!  Use heuristic only for new instructions being added to visible list, but not for the ones that are already shown. In its current state, I find it unusable. Sorry.

In fact, I see this as a regression. It's something that worked well on the classic debugger and can't understand why it can't be implemented the same way.  Why to change something that works fine?

**Comment by m9710797** [comment] 2024-05-21 18:35
The code is doing something "unusual": when stepping through the code, the same code that is being displayed is also being modified. How can the disassembly view know what changes are intended and should be shown, and what changes should not be shown?

E.g. consider a piece of code like this:
```
       ld (instr+2),a   ; modify the offset in the next instruction
instr: ld (ix+0),b      ; the offset '0' will be updated
```
Then obviously while executing the 1st instruction you want the disassembly for the 2nd instruction to be updated. No?
And this is a simple example, you can also imagine stuff like `00 xx yy` -> `01 xx yy` to change `nop ; xxyy` into a `ld bc,xxyy` instruction as a way to disable the instruction formed by `xx yy` (and yes, I have seen this trick in real code).

Your case is basically the same: during the CALL instruction you modify the instructions(*1) that are visible. And because of variable-length Z80 instructions this unfortunately results in "scrambled" instructions on the boundary between a data and a code section.
(*1) I understand that your code change data, not instructions. But there's no way for the disassembly view to understand this distinction.

The only reason why this (seemed to) work with the old debugger is because it did not update the disassembly view correctly. E.g. try viewing a region that contains the JIFFY variable (0xfc9e) (e.g. while the emulation is running). In the old debugger you see a static, but outdated, view. In the new debugger you always see the actual values. This lack of auto-update was the most common complaint about the old debugger.

I do agree that in this _very_ specific scenario it's unfortunate. But I don't know how to improve that. I don't think it's realistic to expect the debugger the figure out what parts of the memory contain data and which parts contain code.

**Comment by Colpocorto** [comment] 2024-05-21 22:00
There isn't any self-modifying code. The only writings are variables that are _before_ the first line of code, so it shouldn't affect the code that had already previously disassembled.

The problem is that the disassembler is disassembling the whole viewport on every step. Ironically, this wouldn't happen with the classic disassembler because of its long term non-refreshing issue.

My proposal:

-A memory address has been written to:
  -If the address is currently in the viewport (disassembled and printed), do NOT refresh on the disassembly screen (do it on the hex view window only).
  -If the address is out of the view scope, the updated content will be disassembled and printed when the address is eventually printed on screen (if ever).

The behaviour above would be configurable with a switch/button, so the user can choose whether the code seen on the viewport must be updated in real time or not (in other scenarios where the code actually modifies itself, the current behaviour would be desirable).  I would also add some visual notification when a code on screen has been just self-modified (e.g. highlight the line with a bright colour and fade it out during the next few seconds).  This FX would help the user understand what has just happened.
