### ISSUE TITLE
audio bug

### ISSUE THREAD

**Issue by thegeps** [openMSX/openMSX#1256] opened 2020-05-08 17:43 UTC
OpenMSX and BlueMSX seem to badly play the fast pitch effect. It sounds like old seventies sci-fi movies computer glitches instead of the right FX. WebMSX and real msx1 hardware play it properly...

https://youtu.be/6gstVuLj_CY

**Comment by MBilderbeek** [comment] 2020-05-08 18:09
Thanks, can you provide a test ROM please?

**Comment by thegeps** [comment] 2020-05-09 07:27
yes, of course!

Il Ven 8 Mag 2020, 20:09 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-09 12:45
OK, I'll await it..

**Comment by thegeps** [comment] 2020-05-09 12:49
I've sent as attachment in prev mail

Il Sab 9 Mag 2020, 14:45 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-09 13:14
Ah, but that doesn't seem to work. I don't think the ticket system accepts attachments of any type when a post is sent via e-mail. Can you attach the file (perhaps renamed) to the ticket in a comment via the website, please?

**Comment by thegeps** [comment] 2020-05-09 13:16
Ok, I'll do. I'm sorry, it's my first ticket and I thought you contacted me
directly by mail LoL

Il Sab 9 Mag 2020, 15:15 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-09 13:20
Yeah, no problem! :) I already suspected something like that was going on :)

**Comment by thegeps** [comment] 2020-05-09 13:22
https://1drv.ms/u/s!Auz5lIVk2TPQbDna9WvKu-vBE90

**Comment by MBilderbeek** [comment] 2020-05-09 13:40
[test.rom.gz](https://github.com/openMSX/openMSX/files/4603522/test.rom.gz)

The effects starts 12 seconds after the tune starts.

**Comment by thegeps** [comment] 2020-05-09 13:49
I have to check on arkos tracker in my pc because the song was composed by
anothet person for my game (but less or more what you said is right)

Il Sab 9 Mag 2020, 15:40 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-09 14:31
It looks like the effect is purely on PSG channel 2 right?

It may help if you can make a ROM with only channel 2, so I can verify. Is that possible? (There is alas no channel mute on WebMSX.)

**Comment by thegeps** [comment] 2020-05-09 15:09
We have 2 effects:
Fast pitch up with speed in channel 2
And after few time (16 pattern rows from 020h to 030h) in channel 2 start
the fast pitch down with speed

https://1drv.ms/u/s!Auz5lIVk2TPQbDna9WvKu-vBE90

https://1drv.ms/u/s!Auz5lIVk2TPQbYLNOthqfcdyeNk


Il Sab 9 Mag 2020, 16:31 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by thegeps** [comment] 2020-05-09 15:11
I don't know how to extract only a channel (or two). So I have to ask it to my composer if you really need it

**Comment by happppp** [comment] 2020-05-09 16:19
If I fill RAM at power-on with 0, it sounds ok, If I fill RAM with $FF I get the bug.

In other words, the game didn't initialize(zerofill) the RAM block that it uses. I expect the bug to happen on some MSX models that have RAM chips filled with $FF at power-on.

**Comment by m9710797** [comment] 2020-05-09 16:31
Thanks a lot happppp! 

I can confirm this. I hacked the test-ROM to fill the RAM when it starts:
* If I fill with 00 then it works in openMSX (and other emulators).
* If I fill with FF then it breaks in WebMSX (and other emulators).
Like happppp said, you cannot rely upon the content of the RAM when the MSX boots. So this is a bug that must be solved in the ROM rather than in the emulators.

I'm closing this ticket.

**Closed as completed by m9710797** 2020-05-09 16:31 UTC
Labels: Sound, PSG

**Comment by MBilderbeek** [comment] 2020-05-09 17:22
@thegeps Which real machine did you use for your test? Perhaps you can make a RAM dump, so that we can see which initial pattern is in there.

**Comment by thegeps** [comment] 2020-05-09 17:37
I used a Philips VG8020/40 (wich I haven't found on openMSX machines, so I use a simple vg8020 set to test on openMSX). I can test on a real vg8235/00 msx2 too if it is needed. About RAM filling: you talk about arkos tracker ram buffer? I'll try

**Comment by m9710797** [comment] 2020-05-09 17:45
@thegeps: any RAM which is read before it's initialized (written).  This is a so called UMR bug (Uninitialized Memory Read).

Note that not all MSX machines, not even all Philips VG8020 machines, are guaranteed to have the same RAM content after boot. This stuff depends on the exact RAM chip type (in principle, possibly even the production date) and there's no guarantee all Philips VG8020 machines use the exact same RAM chips.

**Comment by MBilderbeek** [comment] 2020-05-09 17:46
@thegeps But if you can dump the RAM of your VG 8020/40 with SAVEROM.COM on the RAM slot, we can see it happening in openMSX.

**Comment by thegeps** [comment] 2020-05-09 18:06
saverom.com? where can I find it? (never ear about it and obviously never used). where the dump will be saved? it can be saved in my SD mapper? Let me know how I can be useful ;)

anyway, clearing the small (256bytes) buffer that arkos tracker reserve in RAM for its ROM player solved the issue ^_^ now all music and sound FX play fine in openMSX too. I'm happy!

**Comment by MBilderbeek** [comment] 2020-05-09 18:33
You can find it here: http://frs.badcoffee.info/files/MSX_machine_reverse_engineering_utils.zip

Yes, it can save on your SD mapper, I guess. As long as you can run MSX-DOS (1 or 2), you can run this program. Save the slot of the RAM (slot 3-2, normally), from 0 to FFFF.

**Comment by thegeps** [comment] 2020-05-09 18:41
Ok, I'll try it tomorrow

Il Sab 9 Mag 2020, 20:33 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by theNestruo** [comment] 2020-05-09 20:11
Related isuse: https://github.com/openMSX/openMSX/issues/1249

**Comment by MBilderbeek** [comment] 2020-05-14 20:24
@thegeps Did you try? :)

**Comment by thegeps** [comment] 2020-05-14 20:29
I haven't the time to do. I promise I'll try tomorrow

Il Gio 14 Mag 2020, 22:24 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by thegeps** [comment] 2020-05-15 13:54
Here's RAM dump (I did the ROM dump too, now I'll post it to MRC)

https://1drv.ms/u/s!Auz5lIVk2TPQb5ptUNNQ1lT177M?e=1Ded7U

**Comment by MBilderbeek** [comment] 2020-05-16 10:49
That RAM dump shows a consistent 00 FF pattern. But after adding it to the VG 8020/20 machine, it still didn't work. I don't know why. The ROM dump is identical to the 8020/20 as well.

**Comment by thegeps** [comment] 2020-05-16 10:58
Maybe it is influenced by SD mapper software? When I've turned on my MSX
automatically it started sofarun. I had to press esc to exit to dos and use
saverom.com... and before starting sofarun it booted nestor too (I haven't
an external disk drive so it is the only way I can launch saverom.com)

Il Sab 16 Mag 2020, 12:49 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-16 11:01
Your SD mapper also has RAM, right? Probably SofaRun, Nextor, etc. all used the RAM of the SD mapper.
Your SLOT3-2 dump is completely that 00 FF pattern, nothing else. So it looks like it wasn't used at all.

**Comment by thegeps** [comment] 2020-05-16 11:06
Yeah, you are right. It has 1Mb RAM. Did you try to use my ROM dump
(VG8020/40) and my RAM dump to see if it works?

Il Sab 16 Mag 2020, 13:01 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-16 19:13
Wouter just realized that you used the SD mapper on the real MSX as well, right? Then probably also the RAM of the SD mapper was used when Arkos was playing. So we actually need the initial RAM pattern of your SD mapper :) Can you dump the RAM of that device as well?

**Comment by thegeps** [comment] 2020-05-16 19:43
I'll do ;)

Il Sab 16 Mag 2020, 21:13 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-23 20:12
@thegeps any results yet?

**Comment by thegeps** [comment] 2020-05-24 06:54
I'm sorry, I'm focused on coding (msxdev deadline is near) and I didn't
turned on real hardware for some days. If I'll be able I'll do the dump
this week

Il Sab 23 Mag 2020, 22:12 Manuel Bilderbeek <notifications@github.com> ha
scritto:

**Comment by MBilderbeek** [comment] 2020-05-24 08:59
Sure, let's talk about it after msxdev then! Looking forward to your finished entry :)
