### ISSUE TITLE
Active ImGuiSpriteViewer during boot crashes OpenMSX

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1595] opened 2024-03-17 22:30 UTC
OpenMSX tries to access the visibleSprites array beyond `visibleSprites.size()` in line ImGuiSpriteViewer.cc:596 and receives SIGABRT:

```
#0  0x00007ffff73cd834 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff737b8ee in raise () at /lib64/libc.so.6
#2  0x00007ffff73638ff in abort () at /lib64/libc.so.6
#3  0x00007ffff76d9580 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () at /lib64/libstdc++.so.6
#4  0x0000000000dbf57e in std::span<openmsx::SpriteChecker::SpriteInfo, 18446744073709551615ul>::operator[]
    (this=0x7ffffffec510, __idx=9) at /usr/include/c++/13/span:282
#5  0x0000000000dbd0d9 in operator() (__closure=0x7ffffffec800) at src/imgui/ImGuiSpriteViewer.cc:596
```

This only happens if the VDP Sprite Viewer debuggable is opened during boot and when `msx2` machine is used (HB-F900).

**Comment by MBilderbeek** [comment] 2024-03-17 22:54
I can't get it to crash, but I do see this in valgrind:
```
$ valgrind openmsx -machine Sony_HB-F900 
==410216== Memcheck, a memory error detector
==410216== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==410216== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==410216== Command: openmsx -machine Sony_HB-F900
==410216== 
==410216== Invalid write of size 8
==410216==    at 0x6915D45: ??? (in /usr/lib/x86_64-linux-gnu/liblzma.so.5.6.0)
==410216==    by 0x68F881B: ??? (in /usr/lib/x86_64-linux-gnu/liblzma.so.5.6.0)
==410216==    by 0x6A00000006: ???
==410216==    by 0x63D9B0F: ???
==410216==    by 0x800F8BFEB72567FF: ???
==410216==    by 0x1FFEFFF92F: ???
==410216==    by 0x400EFAA: elf_machine_rela (dl-machine.h:300)
==410216==    by 0x400EFAA: elf_dynamic_do_Rela (do-rel.h:147)
==410216==    by 0x400EFAA: _dl_relocate_object (dl-reloc.c:301)
==410216==    by 0x63E737F: ???
==410216==    by 0x6A2D02F: ???
==410216==    by 0x1FFEFFF8BF: ???
==410216==  Address 0x1ffeffe9d8 is on thread 1's stack
==410216==  136 bytes below stack pointer
==410216== 
==410216== Conditional jump or move depends on uninitialised value(s)
==410216==    at 0xB80957: openmsx::SpriteConverter::clipPattern(int&, unsigned int&, int, int) (SpriteConverter.hh:70)
==410216==    by 0xB7E826: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}::operator()() const (ImGuiSpriteViewer.cc:589)
==410216==    by 0xB8044B: bool im::TreeNode<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}>(char const*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}) (ImGuiCpp.hh:324)
==410216==    by 0xB7FDED: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const (ImGuiSpriteViewer.cc:471)
==410216==    by 0xB80662: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:66)
==410216==    by 0xB80491: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:72)
==410216==    by 0xB7FE81: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*) (ImGuiSpriteViewer.cc:148)
==410216==    by 0xAE5216: openmsx::ImGuiManager::paintImGui() (ImGuiManager.cc:439)
==410216==    by 0xAC19F0: openmsx::ImGuiLayer::paint(openmsx::OutputSurface&) (ImGuiLayer.cc:28)
==410216==    by 0x137E537: openmsx::Display::repaintImpl(openmsx::OutputSurface&) (Display.cc:367)
==410216==    by 0x137E412: openmsx::Display::repaintImpl() (Display.cc:346)
==410216==    by 0x13BFE89: openmsx::SDLVideoSystem::repaint() (SDLVideoSystem.cc:191)
==410216== 
==410216== Conditional jump or move depends on uninitialised value(s)
==410216==    at 0xB80994: openmsx::SpriteConverter::clipPattern(int&, unsigned int&, int, int) (SpriteConverter.hh:79)
==410216==    by 0xB7E826: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}::operator()() const (ImGuiSpriteViewer.cc:589)
==410216==    by 0xB8044B: bool im::TreeNode<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}>(char const*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}) (ImGuiCpp.hh:324)
==410216==    by 0xB7FDED: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const (ImGuiSpriteViewer.cc:471)
==410216==    by 0xB80662: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:66)
==410216==    by 0xB80491: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:72)
==410216==    by 0xB7FE81: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*) (ImGuiSpriteViewer.cc:148)
==410216==    by 0xAE5216: openmsx::ImGuiManager::paintImGui() (ImGuiManager.cc:439)
==410216==    by 0xAC19F0: openmsx::ImGuiLayer::paint(openmsx::OutputSurface&) (ImGuiLayer.cc:28)
==410216==    by 0x137E537: openmsx::Display::repaintImpl(openmsx::OutputSurface&) (Display.cc:367)
==410216==    by 0x137E412: openmsx::Display::repaintImpl() (Display.cc:346)
==410216==    by 0x13BFE89: openmsx::SDLVideoSystem::repaint() (SDLVideoSystem.cc:191)
==410216== 
==410216== Conditional jump or move depends on uninitialised value(s)
==410216==    at 0xB7E941: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}::operator()() const (ImGuiSpriteViewer.cc:591)
==410216==    by 0xB8044B: bool im::TreeNode<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}>(char const*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const::{lambda()#4}) (ImGuiCpp.hh:324)
==410216==    by 0xB7FDED: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}::operator()() const (ImGuiSpriteViewer.cc:471)
==410216==    by 0xB80662: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, int, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:66)
==410216==    by 0xB80491: void im::Window<openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}>(char const*, bool*, openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*)::{lambda()#1}) (ImGuiCpp.hh:72)
==410216==    by 0xB7FE81: openmsx::ImGuiSpriteViewer::paint(openmsx::MSXMotherBoard*) (ImGuiSpriteViewer.cc:148)
==410216==    by 0xAE5216: openmsx::ImGuiManager::paintImGui() (ImGuiManager.cc:439)
==410216==    by 0xAC19F0: openmsx::ImGuiLayer::paint(openmsx::OutputSurface&) (ImGuiLayer.cc:28)
==410216==    by 0x137E537: openmsx::Display::repaintImpl(openmsx::OutputSurface&) (Display.cc:367)
==410216==    by 0x137E412: openmsx::Display::repaintImpl() (Display.cc:346)
==410216==    by 0x13BFE89: openmsx::SDLVideoSystem::repaint() (SDLVideoSystem.cc:191)
==410216==    by 0x137E5E8: openmsx::Display::repaint() (Display.cc:376)
```

**Comment by MBilderbeek** [comment] 2024-03-17 23:00
I also got this when trying to run Lily's Saga with the Boosted MSX2 EN and the Sprite Viewer enabled in a debug build:
```
$ openmsx /tmp/MSXdev22_Lilly\'sSaga-TheStonesofEvergreen_v1.2.rom 
/usr/include/c++/13/span:282: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](size_type) const [with _Type = openmsx::SpriteChecker::SpriteInfo; long unsigned int _Extent = 18446744073709551615; reference = openmsx::SpriteChecker::SpriteInfo&; size_type = long unsigned int]: Assertion '__idx < size()' failed.

```

**Comment by MBilderbeek** [comment] 2024-03-17 23:08
When using an opt build, it didn't crash, but I tried Lily's Saga again and it shows all kinds of weird patterns in the rendered sprites part:
![image](https://github.com/openMSX/openMSX/assets/12675978/f7ff15ad-e546-4454-a378-4f39886108d0)
This is also reported by the author Bengalack on https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=88 and https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=87 
I wouldn't be surprised if these patterns are there because of this UMR bug.

Try the software from here: https://www.msxdev.org/wp-content/uploads/2022/10/MSXdev22_LillysSaga-TheStonesofEvergreen_v1.2.zip

**Comment by m9710797** [comment] 2024-03-18 19:44
All these issues should be fixed now. At least I can't reproduce them anymore.

**Closed as completed by m9710797** 2024-03-18 19:44 UTC
