### ISSUE TITLE
90 degrees screen rotation

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1778] opened 2024-10-08 19:23 UTC
Hello,

I haven't found this feature on the documentation.

An option to rotate the screen 90º would be nice. I don't mean the rotation as in mobile devices, I mean actual rotation of the screen, what would be useful to develop arcade games that need a vertical TV set.

This is an example of a game whose development would benefit from this feature:

https://retroworks.itch.io/destroyer-msx

**Comment by MBilderbeek** [comment] 2024-10-09 07:38
This is a duplicate of #1054 - so closing. Feel free to add new information there.

**Closed as completed by MBilderbeek** 2024-10-09 07:38 UTC
