### ISSUE TITLE
Segfault when compressing snapshot

### ISSUE THREAD

**Issue by mthuurne** [openMSX/openMSX#1201] opened 2019-11-28 03:57 UTC
@Emily82 reported on IRC that openMSX can crash after running for a few seconds. We managed to get a backtrace and the segfault happens inside `LZ4::compress()`. Emily also built the commit just before LZ4 compression was introduced and the commit just after, and the crash only happens with LZ4 and not with Snappy.

It seems to happen more frequently on some MSX models, but I can reproduce it with C-BIOS MSX2+ by running with throttle disabled for a few seconds and then pressing PgUp a few times. Emily reported that for a Philips NMS 8255 just letting it run in BASIC for a while will also trigger a crash. Disabling the reverse feature avoids the crash, which further confirms that the problem is in the snapshot compression.

What is strange about this problem is that it happens in `opt` builds but not in `devel` builds. After closer examination, it turns out that `-O2` doesn't trigger the problem and `-O3` does. The specific optimization flags needed to trigger it are `-ftree-loop-vectorize` and `-fvect-cost-model=dynamic`. This suggests that loop vectorization plays a role in this problem.

Emily is using GCC 7.4.0 on Kubuntu Linux, while I can reproduce the problem with GCC 7.4.1 on openSUSE Linux, both compiling for x86-64.

By adding debug prints, I narrowed down the moment of the crash to this [`unalignedStore32`](https://github.com/openMSX/openMSX/blob/7c46c18bb13237d77f9e67f7fb36affc8484f7e2/src/utils/lz4.cc#L451) statement. If I replace that statement by `op[0] = 0xFF; op[1] = 0xFF; op[2] = 0xFF; op[3] = 0xFF;`, the crash disappears, while that should be functionally equivalent. If I keep both the `unalignedStore32` and the `op[0] = 0xFF; ...` lines, the crash disappears. This suggests that this store itself is not the problem, but the way code is optimized around it.

My guess is that either we're using undefined behavior that only happens to be critical under heavy optimization, or we're triggering a compiler bug. In any case, further investigation is needed.

**Comment by m9710797** [comment] 2019-11-28 09:29
I think it's a bug in our implementation of unalignedStore()   (src/utils/aligned.hh, line 29).

Depending on the value of the "OPENMSX_UNALIGNED_MEMORY_ACCESS" constant, we implement an unaligned store either with a memcpy() or directly as a store instruction (with a reinterpret_cast on the pointer).

On x86 we set this constant to true (so do the direct store). And x86 can indeed handle unaligned load/stores on scalars. However after optimization the compiler may have grouped several scalar load/stores into (fewer) vector load/store instructions. And when the compiler chooses SSE2 load/store instructions then there ARE alignment requirements.

I haven't verified any of this yet, but if my above assumptions are correct then it's not a compiler bug, but undefined behavior in our code.

It should be easy to fix: make unalignedStore() always do the memcpy(). Modern compilers are smart enough to implement such memcpy()s with a single store instruction (when that's allowed by the target CPU).

More general: we should eliminate all uses of 'OPENMSX_UNALIGNED_MEMORY_ACCESS' from our code base. I'll try to do this later this evening when I'm back at home.

**Comment by m9710797** [comment] 2019-11-28 18:45
Should be fixed in 9171f2d82d29. At least I can't reproduce the crash anymore. But please verify.

**Closed as completed by m9710797** 2019-11-28 18:45 UTC
