### ISSUE TITLE
[Bug] 3x SaI crash on windows [sf#463]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#857] opened 2015-06-24 09:48 UTC
**Reported by vampier on 2013-02-03 21:36 UTC**
tested on revision 13148 (current when I type this)

This crash occurs when I switch to 3x SaI on the SDL/SDLGL-FB16 and SDLGL-FB32  renderer. SDL-PP works fine.

Stack trace:

ntdll.dll!000007fecbfea27b() Unknown
ntdll.dll!000007fecbfef0d4() Unknown
ntdll.dll!000007fecc00bd8a() Unknown
AcLayers.dll!000007fea4a49391()  Unknown
&gt;    openmsx.exe!free(void * pBlock) Line 51 C
openmsx.exe!_aligned_free(void * memblock) Line 473   C
openmsx.exe!openmsx::StretchScalerOutputBase&lt;unsigned int&gt;::~StretchScalerOutputBase&lt;unsigned int&gt;() Line 115    C++
openmsx.exe!openmsx::StretchScalerOutput&lt;unsigned int&gt;::`scalar deleting destructor'(unsigned int)    C++
openmsx.exe!openmsx::FBPostProcessor&lt;unsigned int&gt;::paint(openmsx::OutputSurface & output) Line 387    C++
openmsx.exe!openmsx::Display::repaint(openmsx::OutputSurface & surface) Line 410 C++
openmsx.exe!openmsx::Display::repaint() Line 396 C++
openmsx.exe!openmsx::Display::signalEvent(const std::shared_ptr&lt;openmsx::Event const &gt; & event) Line 247  C++
openmsx.exe!openmsx::EventDistributor::deliverEvents() Line 114  C++
openmsx.exe!openmsx::Reactor::run(openmsx::CommandLineParser & parser) Line 580  C++
openmsx.exe!openmsx::SDL_main(int argc, char * * argv) Line 159   C++
openmsx.exe!main(int argc, char * * argv) Line 315 C
openmsx.exe!__tmainCRTStartup() Line 241   C
kernel32.dll!000007fecb79167e()  Unknown
ntdll.dll!000007fecbf1c3f1() Unknown

free.c is a VS2012 component: *void free(pblock) - free a block in the heap

**Comment by MBilderbeek** [comment] 2016-04-27 18:58
Just tried that on a recent version on Windows 8 and I can't reproduce it. Closing.

**Closed as completed by MBilderbeek** 2016-04-27 18:58 UTC
Labels: Graphics
