### ISSUE TITLE
[Bug]V9990 p-mode sprite priority (P1 and P2)

### ISSUE THREAD

**Issue by GhostwriterP** [openMSX/openMSX#1183] opened 2019-09-18 09:43 UTC
As we all know sprite priority among sprites is controlled with order in spat, where the sprite with lowest sprite no. has the higher priority, nothing new here.

Additionally on V9990 in p-mode you can control the (tile) layer / sprite priority with the pr1 bit in the 'additional info' of the sprite. When the bit is set then the sprite is displayed behind the layer and in front when reset. So far so good.

Interesting becomes the case where a sprite with an higher priority is put behind the layer (pr1 set) and another sprite with a lower priority is put in front of the layer (pr1 reset).

In high level the vdp looks up for a pixel out of the (16 pre-selected) sprites and picks the pixel from the sprite with highest priority, then it checks this with the (tile) layer pixel and based on layer/sprite priority either the pixel of the sprite or layer is displayed.

But, what about the sprite in front of the layer? Well it has a lower priority so its pixel is not looked at and simply not displayed.

So basically higher priority sprites behind the layer can be used to mask lower priority sprites in front of the layer.
Undoubtedly this feature could be utilised for some nice effect.

Since this is an openMSX topic Wink , in openMSX two things are emulated incorrectly:

1. the sprite with lower priority with pr1 reset is displayed in front of a sprite with higher priority with pr1 set. Note that priority among sprites is and should solely be controlled by order in spat.

2. no 'masking' behaviour as described above, instead the lower priority sprite is shown (maybe entwined with 1.).

Please find attached a demo which shows this behaviour:
[p1spriteprio.zip](https://github.com/openMSX/openMSX/files/3625563/p1spriteprio.zip)

There is a photo included that shows what it should look like on real msx; in wording:
the blue smileys should go behind and not in front of the centre stripe,
the red smileys should create some silhouette effect,
the green smileys should be masked with a big dots pattern. 

Have fun fixing this one!

**Comment by D15C0DE** [comment] 2019-09-18 18:18
The problem that causes this is that openMSX draws first *all* sprites behind background, then draws the background, and then draws *all* sprites on top of background. In other words, it splits the single sprite layer into two separate layers.

The real hardware only draws each pixel once, deciding for each pixel the highest priority.

**Comment by m9710797** [comment] 2019-09-18 18:23
@GhostwriterP : thanks for your detailed bug report! I'll try to look into this soon. (But I'm also rather busy, so probably not this week anymore).

**Comment by D15C0DE** [comment] 2019-09-18 18:28
A possible implementation in openMSX could be to have a priority buffer for the sprites, where the 'sprites-behind-bg' for each pixel put their sprite number. The 'sprites-on-top' could then check this buffer and not draw when a higher priority sprite exists on that pixel already.

**Comment by m9710797** [comment] 2019-09-23 17:49
Quick update:
I have a local version that seems to fix this problem. Though it's not yet fully ready to commit:
- Still needs more testing on other software (but your test case fully works now).
- Need to cleanup and comment the code better.
- Need to write a detailed commit message explaining the approach.
I hope to finish this one of the following days.

Rough overview of the new drawing algorithm:
- 1st pass: draw background patterns + backdrop
- 2nd pass: draw foreground patterns. And for each pixel remember if it was foreground of background
- 3rd pass: combined front and back sprites: draw sprites from high to low priority, for each non-transparent pixel
  a) check if we've already drawn a sprite on this pixel. If so it must be a higher priority sprite, thus skip.
  b) draw pixel if it's a front-sprite or if it's a back-sprite but not a foreground-pattern-pixel.
  c) mark this pixel as containing a sprite, even if the test in b) failed.
I'll document this better later.

**Comment by m9710797** [comment] 2019-09-25 17:58
Should be fixed now. Pushed as cc2ee6c8ce03c.

**Comment by D15C0DE** [comment] 2019-09-25 20:02
What about P2? (I guess no code review has been done? LMAO)

**Comment by m9710797** [comment] 2019-09-26 17:24
Hmm, you're right. Thanks.
I wrongly assumed that since P2 only has one tile plane it also only has 1 sprite plane.
I'm reopening this bug.

@GhostwriterP: would you be interested in adapting your testcase for P2? I could do it of course, but it would save me some time. Thanks in advance.

**Comment by m9710797** [comment] 2019-10-09 18:27
Ok, I finally got around to testing the P2 behavior on real hardware. Bug confirmed and fixed. I've attached my testcase (modified version of GhostwriterP's testcase).
[p2_spr_test.txt](https://github.com/openMSX/openMSX/files/3708858/p2_spr_test.txt)

I've also shared code between P1 and P2, but it wasn't as easy as D15CODE suggested. See patch (and commit message) for details.

**Closed as completed by m9710797** 2019-10-09 18:27 UTC

**Comment by D15C0DE** [comment] 2019-10-11 01:40
Nice work! I was only talking about the sprites drawing, but you integrated both screen modes entirely :smiley:
