### ISSUE TITLE
[Bug] Media Keys affecting reverse. [sf#408]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#802] opened 2015-06-24 08:41 UTC
**Reported by lexjuh on 2011-03-09 00:17 UTC**
Version: openmsx-0.8.1RC2-windows-vc-x86-bin

on my HP Pavilion dv7 I have media keys build in, to change volumecontrol, playbackcontrols, mute button and HP mediaSmart button.

When I start openMSX, and go back in the reversebar with my mouse and press one of the mediakeys, it affects the reverse replay.

**Comment by openMSX-import** [comment] 2015-06-24 08:45
**Commented by mthuurne on 2011-03-09 00:43 UTC**
Under Linux (X11) with "set kbd_trace_key_presses on", if I press the (un)mute media key on my keyboard, openMSX prints to stderr:

Key released, unicode: 0x0000, keyCode: 0x400000, keyName: PRESS,RELEASE

0x400000 seems to be the flag indicating a key release, since it's present on all key releases, not only media keys. So effectively both the unicode and keycode are 0 for the media key under Linux. However, Alex (the reporter) told me on IRC that he sometimes sees letters appearing in MSX-BASIC when he presses media keys. Log from (un)mute:

Key pressed, unicode: 0x0000, keyCode: 0x00074, keyName: T
Key released, unicode: 0x0000, keyCode: 0x400074, keyName: T,RELEASE

So here the unicode is 0, but the keycode is not. Also, there is both a press and release event, while under Linux there was only a release event (named "PRESS" in the log but that's probably a separate bug).

One way to cope is to ignore key presses with unicode 0. This would work for ordinary keys, but modifiers have a 0 unicode and should not be ignored. Also function keys have a 0 unicode but are relevant as MSX keys. And limiting the ignoring to alphanumeric  and some other printable characters might not be sufficient. So this looks like a problematic approach.

Another approach would be to add some logging inside SDL to see what is coming in there and whether there are any properties of the Windows event that we could use to generate an SDL event that is not a lookalike for another key.

**Comment by MBilderbeek** [comment] 2024-06-02 18:40
I can't reproduce this issue anymore, so closing.

**Closed as completed by MBilderbeek** 2024-06-02 18:40 UTC
Labels: reverse
