### ISSUE TITLE
Emulation of Sony HB-F700D converted to MSX2+ by MK Public Domain

### ISSUE THREAD

**Issue by EMLommers** [openMSX/openMSX#1513] opened 2023-06-23 22:35 UTC
Sony HB-F700D ROM differs from my real Sony HB-F700D
When starting this machine (openMSX), under logo, VRAM amount is mentioned.
My real Sony is mentioning not VRAM but amount of RAM.
Have to extract my Roms from real machine to compare. (Maybe Manuel has them already)

For HB-F700D converted to 2+ I used the roms from blueMSX, lazy to extract roms from real machine.
blueMSX resource page: [http://bluemsx.msxblue.com/resource.html](url)
The HB-F700D converted to 2+ also has the Kun basic upgrade. 
For Kun-Compiler I used the Sanyo basickun.rom
This emulates converted 700D (almost) correcty.

Attached xml for converted 2+ (also changed drives to 2 and RAM to 1024Kb)
[Sony_HB-F700D_2+.xml.txt](https://github.com/openMSX/openMSX/files/11854269/Sony_HB-F700D_2%2B.xml.txt)

**Comment by MBilderbeek** [comment] 2023-06-25 11:22
The question is whether you have the original ROM still in your Sony HB-F700D. Does it actually count the RAM?
I have never seen a Sony MSX2 showing the amount of RAM, it's normally only showing the VRAM, like most MSX2's from Japanese origin. Only Philips ROMs show the RAM and MSX2+/turboR machines. 
Does it say USER RAM (Philips MSX2), Main RAM (MSX2+/turboR) or just RAM (which you said)?
A dump would be most helpful.

So far, my hypothesis is that it is your machine that is different from the original Sony HB-F700D. The dumps used in the openMSX configuration are verified on another real HB-F700D. My own real 700D also only shows VRAM, for instance.

**Comment by EMLommers** [comment] 2023-06-25 11:32
Oeps, I am mistaken in regards of RAM/VRAM message at boot.
The MSX2 mode mentions VRAM  and MSX2+ mode mentions Main RAM.
Because I have it most of time on 2+ mode, I assumed it was same on 2 mode.

When dumping the ROMS I noticed that the KUN compiler ROM was also enabled in MSX2 mode.
Starting with _bc, like Sanyo

Yes, in the 90's I disassembled the RAM check routine, which works on MSX2/2+ incl mapper cartridge.
But on TurboR it did not count the RAM correctly. 468kb  instead of 512kb

I have just dumped the ROMs from my real Sony.
2 packs: 
1x Sony HB-F700D in MSX2 mode
1x Sony HB-F700D in MSX2+ mode

Will create the xml and upload (xml + ROMs)( here when finished.

**Comment by MBilderbeek** [comment] 2023-06-25 13:28
As openMSX project, we intend to emulate machines as they were released. Your MSX2 was customized. We have a way to construct your customized MSX2 with the XML tags as you already did.
But we do not intend to ship customized MSX models of our users with openMSX itself.  

So, I don't think this issue is about something we should do as openMSX project. Everything works as intended and we do not plan to include your particular customized MSX into the openMSX distribution. Although it's fine to share it here of course.

So, this issue can be closed? Or am I missing something?

**Comment by EMLommers** [comment] 2023-06-25 14:01
[Sony HB-F700D MK MSX2 MSX2+ V9958.zip](https://github.com/openMSX/openMSX/files/11859880/Sony.HB-F700D.MK.MSX2.MSX2%2B.V9958.zip)

The ROMs and xml files of HB-F700D Modified by MK Public Domain to 2+

This also has to do with Machine customization. F700D is 'same' as openMSX systemroms , although the SHA1 differs.

Closed!

**Comment by EMLommers** [comment] 2023-06-25 14:07
Also I added in the xml the F4h I/O port.

You can close it if you like...

**Comment by MBilderbeek** [comment] 2023-06-25 14:09
OK, thanks for sharing your config with the world via this ticket. But indeed, I'll close it, as we're not going to do something with it for now.

**Closed as completed by MBilderbeek** 2023-06-25 14:09 UTC
