### ISSUE TITLE
Sex Bomb Bunny flickering graphic

### ISSUE THREAD

**Issue by Anths2016** [openMSX/openMSX#1545] opened 2023-10-12 08:57 UTC
Sex Bomb Bunny flickering graphic. I did not expect Openmsx to lose points to Bluemsx, which instead works correctly.

**Comment by Colpocorto** [comment] 2023-11-08 08:48
That's essentially because the original programmer of Sex Bomb Bunny (someone who has a deep, I mean extremely deep knowledge of the VDP) was involved in the BlueMSX development.

**Comment by MBilderbeek** [comment] 2023-11-08 08:50
This is a duplicate of #471 , so closing. Please continue discussion in that issue.

**Closed as completed by MBilderbeek** 2023-11-08 08:50 UTC
