### ISSUE TITLE
Bug: fullscreen corrupts multi-display settings.

### ISSUE THREAD

**Issue by brawaga** [openMSX/openMSX#1318] opened 2021-01-11 02:48 UTC
Discovered in Linux Mint 18.3, but unlikely to be version-specific, might be OS-specific though.
My workstation has two displays, first is 90° rotated, second has normal orientation. After I return from full screen mode, both are set as normal-oriented, and video is mirrored to both. Very annoying, especially because might be activated just with striking wrong key by mistake.
By the way, while it is not fixed, can I disable ability to switch fullscreen somehow?

**Comment by m9710797** [comment] 2021-01-11 17:07
Hi brawaga,

Thanks for reporting. Seems like a very annoying issue. Though I'm afraid we (the openMSX team) cannot do much about it. To create the window and to switch from/to full-screen mode we use the SDL2 library. OpenMSX itself only calls the 'SDL_SetWindowFullscreen()', and then the SDL2 library handles it. In other words, openMSX itself is totally unaware of screen-rotation and screen mirroring.

Maybe you could verify this by running some random other SDL2 applications (e.g. see https://awesomeopensource.com/projects/sdl2) and try switching full-screen there. I strongly suspect you'll see the same issue. Maybe it also matters which desktop environment (Gnome, KDE, ...) you're using and which display server (X, Wayland, ...). Unfortunately I can't test myself because I only have one monitor. If confirmed, it would be good if you could create a bug report against SDL2 directly.

As a workaround you can disable the default full-screen keybindings by entering these commands in the openMSX console:
`   unbind F11`
`   unbind ALT+RETURN`

Execute the command 'bind' (without any arguments) to see the list of all current bindings.

**Comment by MBilderbeek** [comment] 2021-01-11 18:46
@brawaga  Which openMSX version are you running? If it's older than 16.0, it's still using SDL1, which is significantly older and now unmaintained. Using 16.0 may work a lot better than, as it is using SDL2, as @m9710797 already explained.

**Comment by brawaga** [comment] 2021-01-14 02:47
I use Cinnamin on my Mint, it is Gnome relative if I am not mistaken. I will try something from SDL2 applications list, and come back with results.

Will these unbinds be persistent if we fail to solve the issue? Or I will have to do it each time I run it?

$ openmsx --version
openMSX 0.12.0
flavour: debian
components: CORE GL LASERDISC
I will try to upgrade and bring results back.

**Comment by brawaga** [comment] 2021-01-14 07:30
Unfortunately, 0.12.0 is the latest version available to install. By the way, I approve the issue is SDL2-related, SuperTux game behaves the same way. Is the https://bugzilla.libsdl.org/buglist.cgi?quicksearch=fullscreen right site to report the bug? Most recent is 2018 dated.

**Comment by m9710797** [comment] 2021-01-14 17:02
Hi,

By default (un)bind commands are persistent. And you can always check by executing the "bind" command (without any arguments).

OpenMSX version 0.12 is quite old. All the advice I've given you was assuming a more recent version. Though, I think, in many cases it will also be applicable to older versions. If your distribution doesn't ship a more recent openMSX version, you can always try building it yourself, it's not that hard. You can follow the steps in this manual: https://openmsx.org/manual/compile.html

Yes, you have the correct URL for SDL bug reports: https://bugzilla.libsdl.org/.

**Comment by MBilderbeek** [comment] 2021-01-15 22:58
As you are using openMSX 0.12.0, it is very likely you're not using SDL2, but SDL1.2 (at least with openMSX). SDL 1.2 is unmaintained, as far as I know. Anyway, if you tested SuperTux built against SDL2, the issue is still relevant to report. If that SuperTux is built against SDL1.2, I recommend you to build openMSX 16.0 from source and try if that works better.

**Comment by MBilderbeek** [comment] 2021-02-26 20:54
@brawaga Can you test whether it works better with openMSX 16.0?

**Comment by MBilderbeek** [comment] 2021-03-20 13:25
@brawaga Reminder....

**Comment by brawaga** [comment] 2021-05-24 14:04
Sorry for not answering for roo long, what I have to say it is really SDL problem, I tested some applications and they behave the same. I remember I left already an issue, but could not find, so I just made another one: https://github.com/libsdl-org/SDL/issues/4398.
I have only 0.12 version in my package manager.

**Comment by MBilderbeek** [comment] 2021-05-24 15:39
@brawaga OK, thanks, then I will close the issue on our side. 0.12 is very old (about 5.5 years) anyway... you could try to compile openMSX 17.0 yourself, to see whether it's better. This one uses a newer SDL version. You forgot to mention in the SDL bug report which version you use. For the SDL project it's very interesting to know whether the problem still occurs with the latest SDL release. 0.12 is against the obsolete SDL 1.2 anyway, which is definitely not supported anymore.

**Closed as completed by MBilderbeek** 2021-05-24 15:39 UTC
