### ISSUE TITLE
diskmanipulator export hda bgm cause crash

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1478] opened 2023-01-17 11:33 UTC
[BGM.zip](https://github.com/openMSX/openMSX/files/10434545/BGM.zip)

`set power off`
`ext ide`
`diskmanipulator chdir hda /`
`diskmanipulator export hda bgm`

**Comment by denjhang** [comment] 2023-01-17 11:37
https://youtu.be/Mfxozkq2mng

This video shows the breakdown in action.

**Comment by denjhang** [comment] 2023-01-17 16:02
#1473

**Comment by MBilderbeek** [comment] 2023-01-17 18:04
@denjhang Does that last link mean the crash doesn't happen anymore with the fixes for #1473 ? Or does it still occur with the latest openMSX code?

**Comment by denjhang** [comment] 2023-01-17 18:06
> @denjhang Does that last link mean the crash doesn't happen anymore with the fixes for #1473 ? Or does it still occur with the latest openMSX code?

I tested with the latest build and it's still the same.
`openmsx-18.0-518-g8ba6e3875-windows-vc-x64-bin`

**Comment by MBilderbeek** [comment] 2023-01-17 18:53
I cannot reproduce it (on Linux, at least...) 

How did you start up openMSX exactly? I used:
```
$ openmsx -machine Panasonic_FS-A1GT -ext ide -hda BGM.DSK 
```

**Comment by denjhang** [comment] 2023-01-18 02:14
on windows10
`e:`
`cd E:\Program Files\openmsx-18.0-518-g8ba6e3875-windows-vc-x64-bin`
`openmsx.exe -machine Panasonic_FS-A1GT -ext ide -hda BGM.DSK -ext slotexpander -ext ram4mb -ext scc+`

**Comment by denjhang** [comment] 2023-01-18 02:19
There is no problem with the startup statement, but when I use diskexplorer to manually export, I find that diskexplorer will also crash, and some of the exported file names are garbled. I suspect an issue with the filename is causing the crash.

**Comment by denjhang** [comment] 2023-01-18 02:20
> I cannot reproduce it (on Linux, at least...)
> 
> How did you start up openMSX exactly? I used:
> 
> ```
> $ openmsx -machine Panasonic_FS-A1GT -ext ide -hda BGM.DSK 
> ```

I tried your statement, same situation.

**Comment by denjhang** [comment] 2023-01-18 02:57
https://user-images.githubusercontent.com/61811583/213071405-9f1e2541-850f-4389-ba09-d98a5540d848.mp4

diskexplorer also crashed.

**Comment by MBilderbeek** [comment] 2023-01-18 08:55
This is the list of dirs/files it outputs here:
```
$ ls -R1 /tmp/bgm
/tmp/bgm:
0
'~1.tra'
a
_alt
autoexec.bat
b
c
command2.com
command.com
d
dmv1
dmv2
dmv3
dmvft
e
f
g
h
i
j
k
kinrou5.drv
l
m
mcdrv.com
mgsdrv.com
mpk.bin
mpx.com
mpxnv.com
msxdos2.sys
msxdos.sys
n
nextor.sys
o
opx.bin
p
q
r
s
t
trashe~1
u
v
w
x
y
z

/tmp/bgm/0:
'100'$'\337''f_2.bgm'
'100'$'\337''f.bgm'
3d-1.bgr
3d-1p2.bgr
3dturn.bgm
"9607'psc.bgr"
''$'\262\360\354\362\262''psg.bgm'
''$'\274\375\354\337\371''ry.bgm'

/tmp/bgm/a:
ad-12.bgm
aggres.bgm
airwolf.bgm
ajax-rnk.bgm
akiminia.bgm
akuden25.bgm
ankoku.bgr
anna_sor.bgm
art.bgm
axel-f.bgm
''$'\340\340\266\262''.bgr'
''$'\340''鼲.bgr'

/tmp/bgm/_alt:
_alt1
_alt2
_alt3
_alt4
_alt5

/tmp/bgm/_alt/_alt1:
''$'\352''߽'$'\376\371''1.bgr'
''$'\352''߽'$'\376\371''5.bgr'
bgmop2.bgr
bgmop3.bgr
bgmop4.bgr
bgmop5.bgr
bgmop6.bgr
bgmop7.bgr
bgmop8.bgr
ending.bgr
"fight'a.bgr"
"fight'b.bgr"
fuzake.bgr
hokkai.bgr
kodoku.bgr
main1.bgr
main.bgr
menu.bgr
menunv.bgr
rpg1.bgr
rpg2.bgr
rpg5.bgr
"sh3'sam1.bgr"
"sh3'sam2.bgr"
title.bgr
tonma#10.bgr

/tmp/bgm/_alt/_alt2:
"bgm3'fm.bgr"
bgmop1.bgr
bgmop1e1.bgr
bgmop1e2.bgr
bgmop2.bgr
bgmop2e1.bgr
bgmop2e2.bgr
bgmop3.bgr
bgmop3e1.bgr
bgmop4.bgr
bgmop4e1.bgr
bgmop5.bgr
bgmop5e1.bgr
bgmop6.bgr
bgmop6e1.bgr
bgmop6e2.bgr
bgmop7.bgr
bgmop7e1.bgr
bgmop8.bgr
bgmop8e1.bgr
bgmop8e2.bgr
fv2bgm4.bgm
sg-ep.bgr
sg-pp.bgr

/tmp/bgm/_alt/_alt3:
bgm1c2.bgm
bgm2c2.bgm
bgm3c2.bgm
bgm4c2.bgm
bgmop6.bgr
bgmop7.bgr
bgmop8.bgr
nvend.bgm

/tmp/bgm/_alt/_alt4:
bgmop3.bgr
himi.bgm
msx.bgm
next.bgm
nvend.bgm

/tmp/bgm/_alt/_alt5:
bgmop2.bgr
bgmop3.bgr
bgmop4.bgr
bgmop5.bgr
bgmop6.bgr
bgmop7.bgr
bgmop8.bgr
menu.bgm
sw2.bgm

/tmp/bgm/b:
bb-arrng.bgm
bb.bgm
bc23.bgm
bc25.bgm
bc26.bgm
bc27.bgm
bc28.bgm
bc29.bgm
bc30.bgm
bc31.bgm
bc32.bgm
bc33.bgm
bd-samp1.bgm
bd-samp2.bgm
beatasia.bgm
bg-d10.bgm
bg-d11.bgm
bg-d12.bgm
bg-d13.bgm
bg-d14.bgm
bg-d15.bgm
bg-d16.bgm
bg-d17.bgm
bg-d1.bgm
bg-d2.bgm
bg-d3a.bgm
bg-d3.bgm
bg-d4.bgm
bg-d5.bgm
bg-d6.bgm
bg-d7.bgm
bg-d8.bgm
bg-d9.bgm
bgm-01.bgr
bgm01-gs.bgm
bgm-02.bgm
bgm02.bgm
bgm02gs2.bgm
bgm02-gs.bgm
bgm1.bgm
bgmop1b.bgr
bgmop1.bgr
bgmop1c.bgr
bgmop1d.bgr
bgmop1ob.bgr
bgmop2.bgr
bgmop2ob.bgr
bgmop3.bgr
bgmop3ob.bgr
bgmop4b.bgr
bgmop4.bgr
bgmop5b.bgr
bgmop5.bgr
bgmop6.bgr
bgmop7.bgr
bgmop8.bgr
blabla.bgm
bor-psg.bgr
boss.bgm
bri-r3.bgr
burn2-1.bgm

/tmp/bgm/c:
cafe.bgm
cantar.bgm
castle.bgm
casttle.bgm
cat.bgm
cha-2.bgm
china.bgm
'ci-'$'\272\345\360''3.bgm'
'ci'$'\346\375\343\375\344\376''.bgm'
'ci-'$'\272\345\360''ed.bgm'
cikonami.bgm
cimetro.bgm
ci-sega.bgm
ci-tabi.bgm
ci-upl.bgm
ciyspdv4.bgm
clavan.bgm
clear2.bgr
clear3.bgr
clear.bgr
clock.bgm
coma.bgr
crisis.bgm
crocket.bgm
crusade.bgm
cw-azure.bgr
cw-blade.bgr
cw-king2.bgr
cw-king.bgr
cw-run2.bgm
cw-run.bgm
cw-steel.bgm
cw-tune.bgr
cw-vida.bgm
cw-white.bgr
cyber.bgm
cygnus.bgr

/tmp/bgm/d:
dango.bgm
daniel.bgm
dast.bgr
d-bgm1.bgm
d-bgm2.bgm
d-bgm3.bgm
demon.bgm
descript.ion
dim_q.bgr
dq2-endl.bgm
dq3_aref.bgr
dq3_fght.bgm
dq3_hkra.bgm
dq3_jpng.bgm
dq3_prmd.bgm
"dq3_rot'.bgm"
dq3_zoma.bgm
dq4-ote.bgm
dragon.bgm
dsa-rnd1.bgm
''$'\360\345\360''鲹.bgr'

/tmp/bgm/dmv1:
almosend.mwm
angel_01.mwm
angel_06.mwm
angel_09.mwm
angelkit.mwk
autoexec.bas
climax.mwm
crysiste.mwm
diffmove.mwm
diskchr1.bin
diskexec.bas
dreams.mwm
ending.mwm
flying01.mwm
flying02.mwm
flying03.mwm
flying09.mwm
flying13.mwk
flying13.mwm
hertfire.mwm
illucity.mwm
intro1.mwm
intro2.mwm
intro3.mwm
intro.bas
logos.bin
lost.mwm
melahero.mwm
metalcab.mwk
opl4mus.mwk
prolog4.mwm
rearview.mwm
resist.mwm
skyline.mwm
slintro.mwm
slstage1.mwm
sunday.mwm
thesmoke.mwm
titel1.bin
towerdel.mwm
usas.mwm
walkedge.mwm
wavedrvr.bin
wickchld.mwm
wits.mwm
wolves.mwm
ys2battl.mwm
ys4lava.mwm

/tmp/bgm/dmv2:
allpart2.mwm
autoexec.bas
blessing.mwm
bonus.mwm
careless.mwm
crazy.mwm
defbeach.mwm
diskchr2.bin
diskexec.bas
fantasy.mwm
farewell.mwm
grace.mwm
groucho.mwm
helldel.mwm
housie.mwm
ifsl_new.mwm
intro1.mwm
intro2.mwm
intro3.mwm
intro.bas
intro.mwm
johngasm.mwm
karen.mwm
latinbp.mwm
logos.bin
melchior.mwm
mim.mwm
outcast.mwm
palm.mwm
paradise.mwm
proba.mwm
raveneef.mwm
rocknrol.mwm
roopwave.mwk
sjonnie.mwk
sorceria.mwm
tcokints.mwm
tetrys1.mwm
theend.mwm
titel2.bin
twisted2.mwm
vechtuh.mwm
village.mwm
wapenwin.mwm
wavedrvr.bin
xilion.mwm

/tmp/bgm/dmv3:
7spirits.mwm
allpart2.mwm
almosend.mwm
angelkit.mwk
autoexec.bas
battle.mwm
bonus.mwm
boroz.mwm
cantking.mwm
children.mwm
diskchr3.bin
diskexec.bas
dragon.mwm
ending.mwm
fantasy1.mwm
forest.mwm
gameover.mwm
gooddays.mwm
groucho.mwm
heavens.mwm
ice.mwm
illucity.mwm
intro1.mwm
intro2.mwm
intro3.mwm
intro.bas
intro.mwm
jesuis.mwm
jmpincar.mwm
lalala.mwm
lava.mwm
logos.bin
longtime.mwm
melahero.mwm
melchior.mwm
moonfant.mwm
neokobe.mwm
ode.mwm
paradise.mwm
perestra.mwm
plugpray.mwm
puddle.mwm
puyofuck.mwm
reddwarf.mwm
redmont.mwm
ruins.mwm
sjonnie.mwk
slboss.mwm
slintro.mwm
slstage1.mwm
snik.mwm
strmrage.mwm
syonin.mwm
taketime.mwm
tcokints.mwm
tetrys.mwm
titel3.bin
vechtuh.mwm
wavedrvr.bin
without.mwm
wits.mwm
w_shrine.mwm
xilionra.mwm
xvalthem.mwm
yelwsand.mwm
ys2final.mwm

/tmp/bgm/dmvft:
autoexec.bas
bdd3.mwk
bdd3.mwm
bombakit.mwk
bossbgm7.mwm
chill.mwk
chill.mwm
comevoic.mwk
comevoic.mwm
copy2.mwk
copy2.mwm
digit3.mwk
digit3.mwm
dimeplus.mwm
diskchr4.bin
diskexec.bas
drab_one.mwk
drifting.mwk
drifting.mwm
epic.mwk
epic.mwm
expressi.mwk
expressi.mwm
finalkit.mwk
fireshel.mwm
fnorkels.mwk
fnorkels.mwm
frozencl.mwm
gabber.mwk
gabber.mwm
gun.mwk
gun.mwm
hakkuh.mwk
hakkuh.mwm
hurryup.mwk
hurryup.mwm
intro1.mwm
intro2.mwm
intro3.mwm
intro.bas
iodemand.mwk
iodemand.mwm
joritalo.mwk
joritalo.mwm
know_it.mwm
llight.mwk
llight.mwm
logos.bin
lzrdstar.mwk
lzrdstar.mwm
make512k.mwk
makeover.mwm
metaltra.mwk
metaltra.mwm
meteor.mwk
meteor.mwm
nosferat.mwk
nosferat.mwm
omega02.mwk
omega02.mwm
pnjork.mwk
pnjork.mwm
purehous.mwk
purehous.mwm
sense.mwk
sense.mwm
slowdown.mwk
slowdown.mwm
titel4.bin
volcanic.mwm
voodoo.mwk
voodoo.mwm
wavedrvr.bin
woei.mwk
woei.mwm

/tmp/bgm/e:
''$'\350\361\262''.bgr'
earth.bgr
easter.bgm
ending.bgm
endi_spl.bgm
enemy.bgm
eternal.bgm

/tmp/bgm/f:
f0-bb.bgm
fake.bgm
f-boss.bgm
feda-ain.bgm
feshin.bgm
'ff2-'$'\261\274\376\344''.bgm'
'ff2-'$'\362\262\375''.bgm'
ff2-dan2.bgm
ff2-main.bgm
"ff3'cave.bgm"
"ff3'way.bgm"
ff4samba.bgm
field.bgr
fight.bgm
fighting.bgm
final_b.bgm
fire.bgr
firebird.bgm
flawil.bgm
foun_ys1.bgm
fozwel.bgr
fray.bgm
freddy.bgm
free-fm.bgr
ft2end-s.bgm
fv2bgm1.bgm
fv2bgm2.bgm
fv2bgm3.bgm

/tmp/bgm/g:
gallop.bgm
game_fmp.bgm
game_psg.bgm
gemma1.bgm
gemma2.bgm
ggppop.bgm
ghq.bgm
gnc01.bgm
gr2fc-3.bgm
gradius3.bgm
gr.bgm

/tmp/bgm/h:
hamet2-s.bgm
hanage.bgm
happyend.bgm
heat.bgm
hello-bg.bgr
hello.bgm
hibana.bgm
hinotori.bgm
hokora.bgm
huis.bgm
hypno-09.bgm

/tmp/bgm/i:
'ﹼ'$'\255\263''.bgm'
''$'\356\376\356\376\343\260\357''.bgr'
info.bgr
insensat.bgm
intro.bgm
intruder.bgm
itd.bgr
i-tomita.bgr

/tmp/bgm/j:
j-boy.bgm
jesus-02.bgm
justice.bgm

/tmp/bgm/k:
kanashii.bgm
kastell.bgm
khaos.bgr
kindersz.bgm
kinrous.bgm
kodoku.bgr
komorebi.bgm
konami.bgm
krisna2.bgm
kurenai.bgm
kuso14f3.bgm
kuso1p.bgr
kuso3f.bgr
kuso57f2.bgr
kuso66f3.bgr
kuso71f.bgm
kuso72f2.bgm
kuso73f.bgm
kuso75f.bgm
kuso76f.bgm
kuso77f.bgm
kuso78f2.bgm
kuso79f2.bgm
kuso79f.bgm
kuso80f.bgm
kuso81f.bgm
kuso81f.bgr
kuso82f.bgm
kuso84f.bgm
kuso89f.bgr
kuso92f2.bgr
kuso92f.bgr
kyokai.bgm

/tmp/bgm/l:
lab-r.bgm
lagara-s.bgm
lamia.bgm
laydock2.bgm
legend2.bgm
life.bgr
limbo.bgm
liqnitro.bgr
l-s-d.bgm
lubend1.bgm
lubend2.bgm
luie.bgm
lumati.bgm
luopen.bgm
lusentou.bgm
lutot.bgm

/tmp/bgm/m:
m10.bgm
m11.bgm
m12.bgm
m13.bgm
m14.bgm
m1.bgm
m2.bgm
m3.bgm
m4.bgm
m5.bgm
m6.bgm
m7.bgm
m8.bgm
m9.bgm
ma.bgm
maboju.bgm
madcity.bgm
madlamp.bgr
mad-sad.bgm
main2.bgr
main3.bgr
main_yie.bgm
mario.bgm
massage.bgr
mb.bgm
mc.bgm
md.bgm
me.bgm
megafade.bgm
menu.bgm
merengue.bgm
mf.bgm
minue.bgm
miss-r3.bgr
mog.bgm
morning.bgm
morn_puy.bgm
move_a.bgm
ms-pass.bgm
muermo.bgm
musette2.bgm
musette.bgm

/tmp/bgm/n:
"n'.bgr"
nebula-1.bgm
nemesi2f.bgm
neuroid.bgm
ninjya.bgm
'nos'$'\357\266\376''#3.bgm'
'nos'$'\357\266\376''#4.bgm'
nos#5.bgm
nvend.bgm

/tmp/bgm/o:
''$'\363\375\275\340\261''.bgr'
''$'\365\266\262''.bgr'
ohno.bgm
omens.bgm
oneday.bgm
org-001f.bgm
org-001p.bgm
org-010p.bgm
org-32.bgm
org_32.bgm
org-43.bgm
org_43.bgm
origin01.bgr
oth.bgm
o_there.bgm

/tmp/bgm/p:
peace.bgr
pearlbal.bgr
penguin.bgm
polon.bgm
prelude.bgr
prueba.bgm
ptb-st1.bgm
puyo-fin.bgm
puyoop.bgm

/tmp/bgm/q:
qqq.bgr
quarth.bgm
quinpl2.bgm

/tmp/bgm/r:
rafael-s.bgm
rainy.bgr
random.bgm
resort.bgm
rnas_b1.bgm
rnas_b2.bgm
rnas_s1.bgm
rnas_s2.bgm
rnas_s3.bgm
rnas_s4.bgm
rnas_s5.bgm
rnas_ttl.bgm
rnas_v00.bgm
rnas_v10.bgm
rol1.bgm
rona_b1.bgm
rona_b2.bgm
rona_s1.bgm
rona_s2.bgm
rona_s3.bgm
rona_s4.bgm
rona_s5.bgm
rona_tit.sr8
rona_ttl.bgm
rona_v00.bgm
rona_v01.bgm
rona_v10.bgm
rpg3.bgr
rpg4.bgr
"r'psgn05.bgm"
"r'psgn12.bgm"
"r'psgn13.bgm"
'rs3'\'''$'\360\274\376\266''.bgr'
'rs3'\'''$'\276\375\344\263''.bgr'
"rs3'극.bgr"
"rs3'ers2.bgr"
"rs3'erst.bgr"
'rs3'\''&h00.bgr'
'rs3'\''&h0f.bgr'
"rs3'hai.bgr"
"rs3'kaox.bgr"
"rs3'mel.bgr"
"rs3'nd35.bgr"
"rs3'nd59.bgr"
"rs3'nd68.bgr"
"rs3'nd74.bgr"
"rs3'ndb0.bgr"
"rs3'ndb2.bgr"
"rs3'spl1.bgr"
rsayak.bgm
rsbreath.bgr
rudora.bgm

/tmp/bgm/s:
sailen.bgr
sakura.bgm
samba.bgr
sample1.bgr
sample2.bgr
sample5.bgm
sanchis.bgm
sango-op.bgm
sayonara.bgm
s-bgm10.bgm
s-bgm11.bgm
s-bgm12.bgm
s-bgm13.bgm
s-bgm14.bgm
s-bgm15.bgm
s-bgm16.bgm
s-bgm17.bgm
s-bgm18.bgm
s-bgm19.bgm
s-bgm1.bgm
s-bgm20.bgm
s-bgm21.bgm
s-bgm22.bgm
s-bgm23.bgm
s-bgm24.bgm
s-bgm25.bgm
s-bgm26.bgm
s-bgm27.bgm
s-bgm28.bgm
s-bgm29.bgm
s-bgm2.bgm
s-bgm30.bgm
s-bgm31.bgm
s-bgm32.bgm
s-bgm33.bgm
s-bgm34.bgm
s-bgm35.bgm
s-bgm36.bgm
s-bgm37.bgm
s-bgm38.bgm
s-bgm39.bgm
s-bgm3.bgm
s-bgm40.bgm
s-bgm41.bgm
s-bgm42.bgm
s-bgm43.bgm
s-bgm44.bgm
s-bgm45.bgm
s-bgm46.bgm
s-bgm47.bgm
s-bgm48.bgm
s-bgm49.bgm
s-bgm4.bgm
s-bgm50.bgm
s-bgm51.bgm
s-bgm52.bgm
s-bgm53.bgm
s-bgm54.bgm
s-bgm55.bgm
s-bgm56.bgm
s-bgm57.bgm
s-bgm58.bgm
s-bgm59.bgm
s-bgm5.bgm
s-bgm60.bgm
s-bgm61.bgm
s-bgm62.bgm
s-bgm63.bgm
s-bgm6.bgm
s-bgm7.bgm
s-bgm8.bgm
s-bgm9.bgm
seimaga.bgm
sfz-adon.bgm
"sh3'sa10.bgr"
"sh3'sa11.bgr"
"sh3'sa12.bgr"
"sh3'sam3.bgr"
"sh3'sam4.bgr"
"sh3'sam5.bgr"
"sh3'sam6.bgr"
"sh3'sam7.bgr"
"sh3'sam8.bgr"
"sh3'sam9.bgr"
shiawase.bgr
shiori.bgm
shosr000.bgm
silence.bgm
sk2prim.bgm
skmt9605.bgr
'slap!!.bgm'
sleep.bgm
slooow.bgm
'so'$'\362\274\376\254\260''.bgm'
song11.bgm
song12.bgm
song13.bgm
song2.bgm
song4.bgm
song6.bgm
song8.bgm
song9.bgm
sonic2.bgm
sonic.bgm
sor.bgm
sou.bgr
sp2-hond.bgm
spaharri.bgm
spain.bgm
spice0-s.bgm
sprinter.bgm
sss-end.bgm
sss-st1.bgm
sss-st4.bgm
sss-ttl.bgm
st_3_gr2.bgm
steel_r3.bgr
strenge.bgm
survivor.bgm
syntax2.bgr
syntax.bgm
syntax.bgr
syogun.bgm
system10.bgr
system11.bgr
system12.bgr
system13.bgr
system14.bgr
system15.bgr
system16.bgr
system17.bgr
system1.bgr

/tmp/bgm/t:
talk.bgm
talk.bgr
tansu.bgm
tdsmain.bgm
techno.bgm
test-01.bgr
test_ptn.bgr
tetris.bgm
tetris_m.bgm
theraphi.bgr
thunder.bgm
timan1.bgm
title04.bgm
title09.bgm
title10.bgm
title11.bgm
title12.bgm
title13.bgm
title14.bgm
title15.bgm
title23.bgm
title24.bgm
title25.bgm
title26.bgm
title27.bgm
title28.bgm
title29.bgm
title30.bgm
title31.bgm
title32.bgm
title33.bgm
title.bgm
tldm.bgr
tobimaru.bgm
toko.bgm
town_ff2.bgm
trio2.bgm
trio.bgm
troica.bgm
tuisek-s.bgm
twice.bgm

/tmp/bgm/u:
u14.bgr
uaon.bgr
'ud'\''&h01.bgm'
'ud'\''&h02.bgm'
ulri1.bgm
umiyo.bgr

/tmp/bgm/v:
val.bgm
valis-15.bgm
verdant.bgm

/tmp/bgm/w:
walk.bgm
warning.bgm
wide.bgm
wiz-open.bgm

/tmp/bgm/x:
xaiap.bgm
"x'mas.bgm"
xmasend.bgm

/tmp/bgm/y:
yabai.bgr
youkina.bgm
ys1-open.bgm
ys-2b.bgm
ys_2b.bgm
ys-2.bgm
ys_2.bgm
ys2palac.bgm
ys3-06ar.bgm
ys3ent_n.bgm
ys4_fie2.bgm
ysii_2.bgm

/tmp/bgm/z:
_____~1.bgr
_____~~2.bgr
```
Perhaps the problem is that some of these are not allowed on Windows, as you seem to suggest?

Could you narrow it down to see which file exactly causes the crash, by exporting specific directories to pinpoint?

**Comment by denjhang** [comment] 2023-01-18 09:28
I hope you can help me export the three dsk files and send them to me, so that my problem can be solved temporarily. (laughing)

**Comment by denjhang** [comment] 2023-01-18 09:54
You see, it doesn't work starting from the bgm disk folder 0, and neither does  folder a.
https://youtu.be/IzyTmxqCJak

What's interesting is that after openmsx crashes, some files in folder a are exported, but folder 0 has no files exported.

**Comment by denjhang** [comment] 2023-01-18 09:59
Folder b is exported without issue, folder c crashes again.

**Comment by denjhang** [comment] 2023-01-18 10:02
I uploaded screenshots of files in folder a and folder c.
![截图未命名0118180139](https://user-images.githubusercontent.com/61811583/213142448-7a4b4ca0-531e-4f7c-9b31-e82b62dd64d8.jpeg)
![截图未命名0118180203](https://user-images.githubusercontent.com/61811583/213142466-4287e13c-2c13-4a2b-b3d8-e4ded2de9dde.jpeg)

**Comment by MBilderbeek** [comment] 2023-01-18 12:43
This is the result after exporting on Linux.
[exportresultslinux.zip](https://github.com/openMSX/openMSX/files/10446291/exportresultslinux.zip)

It looks like the crash happens with files that have special characters in the names.

Can you start openMSX from Catapult and repeat this, and when it crashed, do you see anything printed in the "Status Info" tab? (This is stdout/stderr output...) Perhaps the issue is about converting characters to UTF-16 (which is used for Windows file system APIs, I believe).

**Comment by MBilderbeek** [comment] 2023-01-18 12:51
This is the dir-listing on turboR of folder 0:
```
.               <dir>  21-05-04 21:43                                           
..              <dir>  21-06-03 14:44                                           
100゜F    BGM      3040 10-05-05  8:56                                           
100゜F_2  BGM      3156 96-09-07 18:46                                           
3D-1     BGR       839 02-05-27  7:48                                           
3D-1P2   BGR       878 02-05-27  7:52                                           
3DTURN   BGM      2560 95-11-04 11:45                                           
9607'PSC BGR      2047 96-08-07  4:23                                           
イみふめイPSG BGM      1124 96-03-18  8:37                                           
シんふ゜るRY  BGM      7001 10-04-10 15:00    
```
and this is folder 'a':
```
.               <dir>  21-06-03 14:44                                           
..              <dir>  21-06-03 14:44                                           
AD-12    BGM      2392 96-07-03 20:10                                           
AGGRES   BGM      4093 95-02-21 16:52                                           
AIRWOLF  BGM      2122 84-01-01  9:00                                           
AJAX-RNK BGM      4899 95-08-31  9:03                                           
AKIMINIA BGM      3692 96-09-06  5:18                                           
AKUDEN25 BGM      1939 95-11-06                                                 
ANKOKU   BGR       847 10-04-10 15:04                                           
ANNA_SOR BGM      3332 95-03-25 17:05                                           
ART      BGM       771 94-08-10 11:22                                           
AXEL-F   BGM      1280 95-11-04 11:45                                           
たたカイ     BGR      1288 02-05-30 14:42                                           
たのシイ     BGR      1525 02-05-30 15:44                                           
 27K in 14 files        16688K free   
```
and this is the first half of c:
```
 Volume in drive A: is A.                                                       
 Directory of A:¥C                                                              
                                                                                
.               <dir>  21-05-04 21:43                                           
..              <dir>  21-06-03 14:44                                           
CAFE     BGM       862 93-05-08 19:54                                           
CANTAR   BGM       285 93-08-18 15:29                                           
CASTLE   BGM      3848 96-01-05 12:29                                           
CASTTLE  BGM      1904 93-05-08 19:52                                           
CAT      BGM      1836 93-11-20  1:29                                           
CHA-2    BGM      2172 95-08-31  9:04                                           
CHINA    BGM      2778 96-08-25 20:34                                           
CI-SEGA  BGM      2231 96-04-29  0:41                                           
CI-TABI  BGM      3159 95-12-22 12:49                                           
CI-UPL   BGM      2568 96-02-15 23:07                                           
CI-コなみ3  BGM      4325 96-06-02 20:02                                           
CI-コなみED BGM      7551 97-08-02 13:47                                           
CIKONAMI BGM      1202 17-10-14  9:38                                           
CIMETRO  BGM      4335 95-08-18 22:16                                           
CIYSPDV4 BGM      7317 95-12-22 12:48                                           
CIにんてんと  BGM      2333 95-12-22 12:47                                           
CLAVAN   BGM       559 90-04-19  5:16                                           
CLEAR    BGR       952 02-05-27 18:13                                           
Press any key to continue                                                      
```

So, the problem really seems to be about 'special' characters.

@m9710797 @grauw  perhaps we should properly transcode these when exporting, similar to what we do with `get_screen`?
They also don't get properly transcoded on Linux, but there the application doesn't crash, the filenames just get invalid encoding points in them.

**Comment by denjhang** [comment] 2023-01-18 13:12
> This is the result after exporting on Linux. [exportresultslinux.zip](https://github.com/openMSX/openMSX/files/10446291/exportresultslinux.zip)
> 
> It looks like the crash happens with files that have special characters in the names.
> 
> Can you start openMSX from Catapult and repeat this, and when it crashed, do you see anything printed in the "Status Info" tab? (This is stdout/stderr output...) Perhaps the issue is about converting characters to UTF-16 (which is used for Windows file system APIs, I believe).

empty
![截图未命名0118211121](https://user-images.githubusercontent.com/61811583/213180356-1af52d19-05bb-4800-9c15-ba7c870d0014.jpeg)

**Comment by denjhang** [comment] 2023-01-18 13:14
[MGS-01.zip](https://github.com/openMSX/openMSX/files/10446586/MGS-01.zip)
[MGS-02.zip](https://github.com/openMSX/openMSX/files/10446590/MGS-02.zip)
I hope you will be able to export both disks as well. This temporarily solves my problem. (again)

**Comment by grauw** [comment] 2023-01-18 17:56
Yep, looks like an encoding problem.

**Comment by m9710797** [comment] 2023-01-18 18:26
@grauw: I think at this point you know the diskmanipulator code better than I do. And you're actively working on this code. Can you then also look at the encoding stuff? No problem if you don't want to, then I'll try to make time for it this weekend.

The class `MsxChar2Unicode` offers 2 methods `msxToUtf8()` and `utf8ToMsx()` to convert between "MSX" and utf8 encoding. I assume we'll need to call these when we translate between a MSX and a host filename.

**Comment by grauw** [comment] 2023-01-18 18:32
Yeah I’ll take a look. Thanks for the pointers.

I hope there are cross-platform OS functions which just take Unicode as input and take care of transcoding that to whatever codepage the filesystem is using automatically (I’m looking at you, Windows).

**Comment by m9710797** [comment] 2023-01-18 19:04
For file handling on windows we already use the windows API functions that take utf16 (or is it UCS2?) input.

But it's fully abstracted away in the openMSX code. In openMSX everything is utf8. Except at the very last moment, on windows, we convert to utf16.

**Comment by MBilderbeek** [comment] 2023-01-18 20:47
> [MGS-01.zip](https://github.com/openMSX/openMSX/files/10446586/MGS-01.zip) [MGS-02.zip](https://github.com/openMSX/openMSX/files/10446590/MGS-02.zip) I hope you will be able to export both disks as well. This temporarily solves my problem. (again)

[MGS-02_files.zip](https://github.com/openMSX/openMSX/files/10450914/MGS-02_files.zip)
[MGS-01_files.zip](https://github.com/openMSX/openMSX/files/10450916/MGS-01_files.zip)
These are the exported folders (with incorrect filenames, but at least you can read them, I guess). We can compare with the output after the transcoding is fixed.

@m9710797 I guess the crash on Windows happened when converting illegal UTF-8 to UTF-16 in that Windows specific part. Perhaps we can do something better than crash/exit?

**Comment by grauw** [comment] 2023-01-20 21:23
@denjhang Should be fixed now. Can you please confirm the fix on Windows? I only tested on MacOS.

**Comment by denjhang** [comment] 2023-01-21 04:18
> @denjhang Should be fixed now. Can you please confirm the fix on Windows? I only tested on MacOS.

Confirmed it was fixed.

**Comment by MBilderbeek** [comment] 2023-01-21 15:23
OK, then we can close it, thanks all!

**Closed as completed by MBilderbeek** 2023-01-21 15:23 UTC
