### ISSUE TITLE
[Bug] Android: slow unlocking from screensaver [sf#452]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#846] opened 2015-06-24 09:47 UTC
**Reported by manuelbi on 2012-12-03 10:03 UTC**
&lt;Quibus&gt; when openMSX is running and the 'screensaver' kicked in (so I have to unlock the device again), this unlocking goes very slowly. Is openMSX using CPU power or is it a memory issue?
&lt;awulms&gt; it might be that openmsx keeps running on the background
&lt;awulms&gt; I must investigate
&lt;Quibus&gt; awulms: well, sound is stopped, at least

**Comment by openMSX-import** [comment] 2015-06-24 09:50
**Commented by awulms on 2012-12-15 14:15 UTC**
Updated openMSX to go into 'blocked' mode when an SDL_ACTIVEVENT 'de-activete' is recieved and to return to 'running' mode when en  SDL_ACTIVEVENT 'activate' is received.

It has significantly improved the situation.

However, openMSX is still using up to 12% CPU when in background, which is more then expected and a drain on the battery. Needs to be further investigated.

**Comment by openMSX-import** [comment] 2015-06-24 09:50
**Commented by awulms on 2013-11-03 15:34 UTC**
Tested today with app "CPU Monitor" and according to "CPU Monitor" app, openMSX uses 0% CPU when it is in background. I tested it on a Samsung Galaxy Nexus with Android 4.3

It would be good if somebody can also test again on a device with an older version of Android.

Test scenario:
-Install app "CPU Monitor" from google-play
-Start recording CPU usage with CPU monitor
-Start openMSX and start a game or demo that uses CPU, VDP and Sound chips
-Send openMSX to background (e.g. by returning to the launcher)
-Wait a minute
-Return to CPU Monitor app
-Stop recording
-View the graph for "openMSX" in CPU Monitor app. On my nexus it drops to 0% as soon as openMSX goes to the background

I don't remember by heart which improvements I did since last year to decrease CPU usage when openMSX is in background.

**Comment by openMSX-import** [comment] 2015-06-24 09:50
**Commented by manuelbi on 2013-11-04 21:34 UTC**
Trying a run of Vampire Killer on my Samsung Galaxy Gio and pressing the button to go to the main menu and forcing openMSX in the background.

<Quibus> awulms: my 'Active applications' display says: 21.58MB RAM usage and 3.14% CPU
<Quibus> it varies a bit between 2 and 4%

**Comment by openMSX-import** [comment] 2015-06-24 09:50
**Commented by manuelbi on 2013-11-04 22:03 UTC**
Perhaps the whole initial issue isn't relevant anymore, because when I test now, my phone does not get into the screensaver mode when I run a game :)

**Comment by MBilderbeek** [comment] 2016-04-27 19:10
Closing as I can't reproduce this issue anymore, as was already mentioned in last comment.

**Closed as completed by MBilderbeek** 2016-04-27 19:10 UTC
