### ISSUE TITLE
[Bug] Mouse emulation lacks arithmetic saturation [sf#498]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#892] opened 2015-06-24 10:02 UTC
**Reported by sd-snatcher on 2013-08-31 17:03 UTC**
This bug is related to the #477.

Interesting enough, just like what happened on Trackball.cc, the mouse emulation also fails arithmetic saturation tests. This means that the same overflow bug happens with the mouse, albeit they're much rarer because the offsets are 8-bit.

But it seems that there was already an attempt to implement the arithmetic saturation on Mouse.cc, but the code is bugged and end up imposing limits to the actual X/Y coordinates instead of the offsets.

The fixed code for the lines 240-243 of Mouse.cc seems to be:

int newX = curxrel - mev.getX();
int newY = curyrel - mev.getY();
int deltaX = max(127, min(-128, newX - curxrel));
int deltaY = max(127, min(-128, newY - curyrel));

**Comment by openMSX-import** [comment] 2015-06-24 10:18
**Updated by m9710797 on 2013-09-01 19:00 UTC**
- **status**: open --> closed-fixed

**Comment by openMSX-import** [comment] 2015-06-24 10:18
**Commented by m9710797 on 2013-09-01 19:00 UTC**
You're right that the original clipping code in the mouse emulation didn't work (it actually clipped on -256..254 instead of -128..127). But I just tested a real MSX mouse (Philips SBC3810) and it doesn't do any clipping at all (so by accident the buggy emulation code was already (closer to) the real behavior).

In revision ebeb2989 I've completely removed the mouse-offset clipping code.

**Comment by openMSX-import** [comment] 2015-06-24 10:18
**Commented by sd-snatcher on 2013-09-02 02:16 UTC**

The Philips mouse may not have clipping, but I have a MK-Mouse II here and it clearly has.

The clipping seems to be implementation dependent. Some mice have, others don't. This happens because the MSX mice are implemented by software on a small microcontroller, so each mouse has a unique algorithm.

If you want to, I may record a video of my MK-Mouse II, similar to the one Werner recorded for the trackball.

**Comment by openMSX-import** [comment] 2015-06-24 10:18
**Commented by m9710797 on 2013-09-02 08:10 UTC**
You can make a video, but I don't think it's really needed (the trackball video _was_ very useful). This is how I tested:

  10 A=PAD(12)
  20 X=PAD(13)
  30 Y=PAD(14)
  40 PRINT X,Y
  50 FORI=0to250;NEXT
  60 GOTO 10

By varying the value '250' in line 50 it's possible to control how frequently the mouse is sampled. I preferred this over physically moving the mouse very fast because I also want to make sure there is no 'mechanical overflow' (I mean if the led/photo-diode doesn't sample the holes fast enough (or however the mechanical construction works) then you'll get aliasing effects and the axis may appear to rotate in the opposite direction).

Anyway, to get 8-bit overflow you already need to move the mouse over (more than) half
the screen width within one mouse-poll-interval (typically 1 or a few 1/50s). That's very fast. I don't believe this is worth the complexity of supporting different mouse models.

**Comment by openMSX-import** [comment] 2015-06-24 10:18
**Commented by sd-snatcher on 2013-09-03 13:37 UTC**

Excellent idea! This test is at the same time simple and very well thought.

I tested the MK-Mouse II using it, and it indeed overflows this way. Then I opened the mouse to check why it didn't overflow in the fast test.

What happens is that the mechanical parts indeed act as a restriction. They just can't spin fast enough to make the counters overflow. The ball will loose traction over the surface, and will also loose traction over the internal wheels. 

In a nutshell, the design has a RPM limit, and that itself act as a "mechanical clip" for the offsets.

**Comment by sdsnatcher** [comment] 2018-08-29 22:43
I ask for this bug report to be reopened. 

The original MSX mice of that time might not have had clipping. But neither the protocol or those mice where ever designed to work at such a high DPI that modern devices have. Not implementing the clipping would be the equivalent of not implementing the scale_factor for the image rendering just because "the original MSX VDP doesn't implement scaling".


I'm talking with the Japanese artist Wakachan, and he's having trouble to use his Wacom drawing pad with openMSX. Whenever he draws too fast, the MSX mouse pointer goes haywire. He can only make it work if he traces it very slowly. 

This obviously restricts the creativity of the artist.

So please, implement the clipping for the mouse device emulation.

**Comment by m9710797** [comment] 2018-08-30 16:36
I doubt this behavior is caused by the high DPI stuff, because overflow/clipping happens after the host mouse offsets have been scaled down to MSX mouse offsets. I *guess* the problem might be related to using a tablet rather than a mouse. Because when you toch the tablet in a new position (in order to behave as a mouse) the tablet has to send relatively large offsets.

Another possibility is that the MSX program is simply too slow to be able to handle fast drawing operations, and therefor starts loosing mouse updates. This can be easily checked by emulating at a faster than real-time speed (e.g. `set speed 500`).

Anyway, I've implemented the following. It might be better than the clipping solution you proposed:

I replaced:
   `xrel = curxrel; yrel = curyrel;`
   `curxrel = 0; curyrel = 0;`
with
   `xrel = Math::clip<-128, 127>(curxrel);`
   `yrel = Math::clip<-128, 127>(curyrel);`
   `curxrel -= xrel;`
   `curyrel -= yrel;`
Where `xrel` and `yrel` are the values that are being send to the MSX. And `curxrel` and `curyrel` are the (scaled down) offsets that track the host mouse.

So when an offset is too large it's now send to the MSX in multiple steps (each step clipped to the maximum possible offset).

Please test and let me know if the problem is solved.

**Comment by sdsnatcher** [comment] 2018-09-04 00:04
Ok, I'll ask him to test.

Since he uses a Mac, I have to wait until a newer build shows up in the [Mac daily builds folder](http://openmsx.fixato.net/builds/mac/x86_64/).

**Comment by MBilderbeek** [comment] 2018-09-05 21:16
Thanks for the reminder, I checked with Niek who runs that auto-builder and he just got it back to work, so there is a new Mac build available right now!

We'll be happy to hear about any results!

**Comment by sdsnatcher** [comment] 2019-05-10 01:22
Wakachan has posted a video of how the mouse pointer problem occurs when he tries to draw on Graph Saurus using his configuration:

**Difference between mouse and pen**
Windows 10 raytrektab + OpenMSX-0.15.0 + GraphSaurus + mouse / wacom Feel Technology(mp4)
http://www.ateliermw.com/cglib/otan2019/jumpingmouse.html

According to him, it's a Windows tablet PC using "wacom feel Technology".

**Comment by MBilderbeek** [comment] 2019-05-12 21:34
So, it works fine with a mouse, but not with the touch screen?
I'm not sure this is something we can do something about... or even how it is related to this ticket.
 (Or do you think it's the overflow problem?? Hard to tell, as we do handle it now, I think...)
But he could try the latest build, perhaps things work better with SDL2, if it's related to the host input side?

**Comment by MBilderbeek** [comment] 2020-05-07 12:11
I see that the mouse cursor is wrapping around when moving very large distances with my host PC mouse. Sometimes it cannot move further and it seems to get stuck against a virtual barrier. Moving the other way and then the original way solves that. But it looks and feels very strange. I would expect no wrapping around at all.

Also reported to @m9710797 .

**Comment by MBilderbeek** [comment] 2020-05-09 17:55
This effect can be reproduced in Philips MSX Designer on the NMS 8220. But not on the MSX-View software on the turboR GT. 

wouterv> ok,   i suspect it's a bug in philips designer.  But i'll check
Quibus> wouterv: I can confirm it's not reproducible on MSX View. Cursor is going a lot slower there anyway
wouterv> yes, if i artifically clip the mouse offsets to [-15,+15] (instead of [-127,+127]) the wrapping stuff in Philips Designer is gone.   So i very much expect this is a limitation in Philips designer
wouterv> it should be doable to reproduce this on a real machine
wouterv> (and it also explains why it's much easier to trigger horizontally than vertically)

So, this wrapping is not a bug in openMSX. Closing again.

**Closed as completed by MBilderbeek** 2020-05-09 17:55 UTC
Labels: mouse
