### ISSUE TITLE
gcc11 build fail

### ISSUE THREAD

**Issue by Pro-pra** [openMSX/openMSX#1458] opened 2022-11-06 12:08 UTC
Hi, have issue for this?

```DEBUG: 	-MP -MMD -MF derived/x86_64-linux-rpm/dep/console/OSDGUI.cc.d \
DEBUG: 	-o derived/x86_64-linux-rpm/obj/console/OSDGUI.cc.o -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic -DNDEBUG -std=gnu++20 -pthread -m64 -pipe -std=c++2a -Wall -Wextra -Wundef -Wno-invalid-offsetof -Wunused-macros -Wdouble-promotion -Wmissing-declarations -Wshadow -Wold-style-cast -Wzero-as-null-pointer-constant -Isrc -Isrc/cassette -Isrc/commands -Isrc/config -Isrc/console -Isrc/cpu -Isrc/debugger -Isrc/events -Isrc/fdc -Isrc/file -Isrc/ide -Isrc/input -Isrc/laserdisc -Isrc/memory -Isrc/resource -Isrc/security -Isrc/serial -Isrc/settings -Isrc/sound -Isrc/thread -Isrc/unittest -Isrc/utils -Isrc/video -Isrc/video/ld -Isrc/video/scalers -Isrc/video/v9990 -Iderived/x86_64-linux-rpm/config -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/tcl8.6.11 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/libpng16 -c src/console/OSDGUI.cc
DEBUG: src/console/CommandConsole.cc: In member function 'void openmsx::CommandConsole::deleteToStartOfWord()':
DEBUG: src/console/CommandConsole.cc:594:26: error: no matching function for call to 'std::basic_string<char>::erase(std::tuple_element<0, std::tuple<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<const char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, unsigned int> >::type&, std::tuple_element<0, std::tuple<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, unsigned int> >::type&)'
DEBUG:   594 |         currentLine.erase(begin, end);
DEBUG:       |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
DEBUG: In file included from /usr/include/c++/11.2.0/string:55,
DEBUG:                  from /usr/include/c++/11.2.0/bits/locale_classes.h:40,
DEBUG:                  from /usr/include/c++/11.2.0/bits/ios_base.h:41,
DEBUG:                  from /usr/include/c++/11.2.0/streambuf:41,
DEBUG:                  from /usr/include/c++/11.2.0/bits/streambuf_iterator.h:35,
DEBUG:                  from /usr/include/c++/11.2.0/iterator:66,
DEBUG:                  from /usr/include/c++/11.2.0/bits/ranges_algobase.h:36,
DEBUG:                  from /usr/include/c++/11.2.0/bits/ranges_algo.h:35,
DEBUG:                  from /usr/include/c++/11.2.0/algorithm:64,
DEBUG:                  from src/utils/stl.hh:4,
DEBUG:                  from src/utils/ranges.hh:4,
DEBUG:                  from src/utils/Subject.hh:5,
DEBUG:                  from src/settings/Setting.hh:4,
DEBUG:                  from src/settings/BooleanSetting.hh:4,
DEBUG:                  from src/console/CommandConsole.hh:6,
DEBUG:                  from src/console/CommandConsole.cc:1:
DEBUG: /usr/include/c++/11.2.0/bits/basic_string.h:4757:7: note: candidate: 'std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::erase(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
DEBUG:  4757 |       erase(size_type __pos = 0, size_type __n = npos)
```

**Comment by Pro-pra** [comment] 2022-11-06 12:10
set -std=gnu++11, -std=gnu++17 and -std=gnu++20 not help me

**Comment by MBilderbeek** [comment] 2022-11-06 13:23
Which code are you compiling? 18.0 or git master? Something else?

**Comment by Pro-pra** [comment] 2022-11-06 13:52
18.0

CommandConsole.cc in git master not have any changes on line 594 (595)

**Comment by m9710797** [comment] 2022-11-06 18:17
Hi,

I just tested:
* Both with gcc-11 and gcc-12.
* Both with the 18.0 version of the source code and the current master branch.
* With OPENMSX_FLAVOUR=devel, opt and debug.
But all combinations compile fine for me.

Can you explain in more detail which version, which flavour, what platform, etc ... you're trying to compile?
Can you paste the full error message?

Line 594 in CommandConsole.cc tries to call the string::erase() method with two const_iterator parameters. There's nothing weird about that. It's already been part of c++11, so I expect it to be well supported (by all compilers).  (openMSX does require c++20 for other parts of the code).
   https://en.cppreference.com/w/cpp/string/basic_string/erase

**Comment by Pro-pra** [comment] 2022-11-07 01:24
Thank you,

full build log: https://file-store.rosalinux.ru/api/v1/file_stores/ad5f7c4bfd5124d2c24171526005b72c8a9c9a6f.log?show=true

rpm spec file based on Fedora spec, https://abf.io/import/openmsx/blob/rosa2021.1/openmsx.spec

**Comment by m9710797** [comment] 2022-11-07 11:06
Hi,

I might have found the problem. If I'm correct then it's a "bug" in your gcc version. I'll try to explain why I think this is the case ...

I looked at the 11.2 version of the libstd++ header files.
The error log you gave points to: /usr/include/c++/11.2.0/bits/basic_string.h:4793:22
That's indeed the erase() overload that's supposed to be called, however this overload only accepts 'iterators', not 'const_iterators'. That conflicts with the (standard c++) documentation of this method.
Next I noticed that on line 1864 in the same file there IS an overload for erase() that DOES take two 'const_iterators'. 
Looking closer I saw that both are located in the then or else block of an "#if _GLIBCXX_USE_CXX11_ABI" (on line 64).

Via google I found this:
    https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
This #define controls whether the compiler should use the standard compliant version, or the older version (for ABI compatibility with gcc-5), of the c++ standard library. Normally gcc defaults to the standard compliant version. But apparently some distributions ship with a gcc version that defaults to the old version.

My hypothesis is that this old version has a bug, or at least it does not conform to the standard specification that says std::string::erase() should be callable with two 'const_iterator' parameters.

To verify my hypothesis I created this test-case:
    https://godbolt.org/z/qd3Gcr6zq
Comment out either line 8 or line 9 to make the test pass, or make it fail with a similar error message as the one you got.


Which gcc version are you using *exactly*?  I mean not just the version number, but shipped by which linux distribution? Do you know if that distribution switches the default for '_GLIBCXX_USE_CXX11_ABI'?   (IIRC some versions of RedHat used to do this???)

Let's first try to confirm if my hypothesis is indeed correct before thinking about a possible solution/workaround.

**Comment by Pro-pra** [comment] 2022-11-08 11:41
i set #define _GLIBCXX_USE_CXX11_ABI 1 in file src/console/CommandConsole.cc - this not help me
#define _GLIBCXX_USE_CXX11_ABI 0 - also not help me :(

**Comment by m9710797** [comment] 2022-11-08 12:11
Just making sure ... where exactly did you add this? It needs to come before any other #include. So preferably add it on the very first line.

As an experiment this is fine: you first need to get the file src/console/CommandConsole.cc to compile fine. But adding this #define in CommandConsole.cc cannot be a final solution.

The reason is that this changes some c++ classes in an incompatible way, and then they don't work together with the same classes compiled in other .cc files. In other words: all .cc files must be compiled with the same value for _GLIBCXX_USE_CXX11_ABI. So instead of adding this #define in every .cc file it's better to pass this as a -D_GLIBCXX_USE_CXX11_ABI=1 compiler flag  (I still have to figure out how to best do that).

**Comment by Pro-pra** [comment] 2022-11-08 12:51
Yes, i add #include after all includes in file :) and it not help me.

Add -D_GLIBCXX_USE_CXX11_ABI=1 to CXXFLAGS make build fine! Oh, on link stage i see undefined reference 
full log [https://file-store.rosalinux.ru/api/v1/file_stores/979a729ddd72eccf615651932ab43395363d0694.log?show=true](https://file-store.rosalinux.ru/api/v1/file_stores/979a729ddd72eccf615651932ab43395363d0694.log?show=true)

Short log: 
```/usr/bin/aarch64-rosa-linux-gnu-ld: derived/aarch64-linux-rpm/obj/commands/TclArgParser.cc.o: in function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const &':
/usr/include/c++/11.2.0/sstream:917: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const &'
collect2: error: ld returned 1 exit status```

Thank, you!

**Comment by Pro-pra** [comment] 2022-11-08 13:31
link with libsdc++.so not help.

attempt add #define _GLIBCXX_USE_CXX11_ABI=1 to src/console/CommandConsole.cc first line.

**Comment by Pro-pra** [comment] 2022-11-08 13:41
> attempt add #define _GLIBCXX_USE_CXX11_ABI=1 to src/console/CommandConsole.cc first line.

Not help, link fail with more undefined reference
>DEBUG: /builddir/build/BUILD/openmsx-18.0/src/console/CommandConsole.cc:152: undefined reference to >`openmsx::FileContext::resolveCreate[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >) const'

**Comment by m9710797** [comment] 2022-11-08 14:04
I did some googling. I found several references to similar problems. But unfortunately without any clear solution :(

The advice I found always boils down to:
   Make sure _everything_ is build with the same setting for _GLIBCXX_USE_CXX11_ABI. This is both the source code of the main project, but possibly also 3rdparty c++ libraries that are linked with that project.
See also the "Troubleshooting" section at the bottom of this page:
   https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Though for openMSX I don't think we link with any c++ libraries. Except for libstdc++, but that's _supposed_ to work with both ABIs.

So I'm not sure how to continue.
Could you switch to a different compiler? One that doesn't require this _GLIBCXX_USE_CXX11_ABI stuff? And then rebuild everything with that compiler.

**Comment by Pro-pra** [comment] 2022-11-09 01:07
Amazing!
Final way:
1. Add to CXXFLAGS  -D_GLIBCXX_USE_CXX11_ABI=1
2. patch file 
```diff -ruN a/src/commands/TclArgParser.hh b/src/commands/TclArgParser.hh
--- a/src/commands/TclArgParser.hh	2022-06-12 22:53:09.000000000 +0900
+++ b/src/commands/TclArgParser.hh	2022-11-09 09:29:49.601554264 +0900
@@ -1,3 +1,4 @@
+#define _GLIBCXX_USE_CXX11_ABI 0
 #ifndef TCLARGPARSER_HH
 #define TCLARGPARSER_HH```

Right way: fix src/console/CommandConsole.cc to work with c++2a abi

**Comment by MBilderbeek** [comment] 2022-12-02 21:37
@m9710797 is there anything to do for us for this ticket?

**Comment by m9710797** [comment] 2022-12-03 08:14
I don't think there's anything we can or should do about this.

The root cause is a non-conforming compiler. So the fix should be to switch to a different compiler.

The workaround provided by Pro-pra might fix the problem today (on one specific platform), but it's too brittle. It might break again if we make (small) changes in TclArgParser, or call a function in TclArgParser from some other context (because all interacting c++ code should really be compiled with the same value for _GLIBCXX_USE_CXX11_ABI).

So I'm closing this ticket  (feel free to re-open if you disagree).

**Closed as completed by m9710797** 2022-12-03 08:14 UTC
