### ISSUE TITLE
[Bug] SDLGL-PP wrong on OS X: top part of screen missing [sf#276]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#577] opened 2015-06-22 19:26 UTC
**Reported by manuelbi on 2007-09-07 21:24 UTC**
When ray2day ran openMSX with SDLGL-PP on his OS X machine, he saw that the top part of the screen is missing, see attached screenshot. Using just SDL worked fine.

**Comment by openMSX-import** [comment] 2015-06-22 19:29
**Commented by manuelbi on 2007-09-07 21:24 UTC**

Attached file Afbeelding%201.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/35f19c1f/d9a1/attachment/Afbeelding%201.png

**Comment by openMSX-import** [comment] 2015-06-22 19:29
**Commented by manuelbi on 2007-11-03 20:51 UTC**
Logged In: YES 
user_id=78178
Originator: YES

ray2day reported that -nopbo solves the problem.

**Comment by openMSX-import** [comment] 2015-06-22 19:29
**Commented by manuelbi on 2007-11-03 21:00 UTC**
Logged In: YES 
user_id=78178
Originator: YES

Note that I have also problems with SDLGL-PP under Linux with an ATI card. They are gone when I use -nopbo.
The problems are a bit different though: I get wrong colours when using interlacing (deinterlace setting doesn't matter). Example: a blue Unknown Reality logo.

**Comment by openMSX-import** [comment] 2015-06-22 19:29
**Commented by manuelbi on 2007-11-25 17:00 UTC**
Logged In: YES 
user_id=78178
Originator: YES

Vampier also reported problems similar to the originally reported problem in this bug report, but then on Windows. Again using an ATI card. On that system, it did not help to use -nopbo, according to him.

Proposed way to follow up: use MESA software rendering and see if everything is working as it should. If not, we know there is a bug in our code and not in the ATI drivers (on 3 platforms; and according to Xorg developers, they are from different sources anyway!).

**Comment by MBilderbeek** [comment] 2020-11-22 22:33
@mthuurne You have an ATI/AMD card, but I bet this doesn't occur (anymore) as the issue is so old. I'll just close it, please reopen in the unlikely case you still see something of this.

**Closed as completed by MBilderbeek** 2020-11-22 22:33 UTC
Labels: Graphics
