### ISSUE TITLE
[Bug] Mouse don't work properly on fullscreen on Mac-OS-X [sf#370]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#764] opened 2015-06-24 06:15 UTC
**Reported by sd-snatcher on 2010-01-10 04:06 UTC**
On Mac OS-X, after you switch openMSX to fullscreen the mouse stops at "virtual barriers". This can only be fixed if you also type "set grabinput on" on the console.

Probably the best solution would be force the mouse to be grabbed when running fullscreen and only use the value of the grabinput setting when running on windowed mode.

Tested configuration info:
- Mac OS X 10.5.8 (intel)
- openMSX 0.7.2
- NekoLauncher openMSX v1.0 (20091203)

**Comment by openMSX-import** [comment] 2015-06-24 06:27
**Commented by sd-snatcher on 2013-08-31 16:46 UTC**
Edit: I moved the mouse saturation issue to a new bug. Some more tests revealed that problem with the "virtual barriers" on Mac OS-X seems related to the real mouse pointer on Mac OS-X hitting the border of the screen when openMSX is on fullscreen.

Mac OS-X seems to handle the mouse coordinates on fullscreen differently from Windows and Linux. The fix for this bug seems indeed to force grabinput when running on fullscreen.

**Comment by openMSX-import** [comment] 2015-06-24 06:27
**Commented by sd-snatcher on 2013-08-31 17:16 UTC**
BTW, this bug affects both the mouse and trackball emulation on Mac OS-X. Probably it will affect anything that gets absolute the mouse coordinates from the OS.

**Comment by openMSX-import** [comment] 2015-06-24 06:27
**Commented by manuelbi on 2013-11-14 20:44 UTC**
I implemented this in revision 0_9_1-653-g4d3d400
Please test on Mac.

**Comment by openMSX-import** [comment] 2015-06-24 06:27
**Updated by manuelbi on 2013-11-14 20:44 UTC**
- **labels**:  --> mac
- **assigned_to**: Manuel Bilderbeek
- **Group**:  --> Next_release

**Comment by openMSX-import** [comment] 2015-06-24 06:28
**Commented by sd-snatcher on 2013-11-27 15:36 UTC**
I tested it and it's working fine now. Thanks!

**Comment by openMSX-import** [comment] 2015-06-24 06:28
**Updated by manuelbi on 2013-11-27 15:52 UTC**
- **status**: open --> closed-fixed

**Comment by openMSX-import** [comment] 2015-06-24 06:28
**Commented by manuelbi on 2013-11-27 15:52 UTC**
OK, thanks for testing!

**Comment by sdsnatcher** [comment] 2020-02-17 01:52
This bug has returned after the SDL2 migration. Is it possible to reopen this ticket, or do I have to open a new one?

**Comment by MBilderbeek** [comment] 2020-02-17 20:15
@sdsnatcher Did you test with the latest development code? We changed something for this in b73b136b7d1c17d966f3f4c7dabcc2c9b279a869 about 1 year ago. At that point @niekniek said he had this problem and I could fix it by reverting the workaround that was done for this ticket.

@niekniek Do you also/again have this issue?

**Comment by sdsnatcher** [comment] 2020-02-17 20:28
For all bugs I reported since last weekend, I used this build: openmsx-0.15.0-342-g340892a03-mac-x86_64-bin.dmg | 2020-02-16 22:00, downloaded from the [openMSX Builder](https://openmsx.fixato.net/builds/mac/x86_64/).

**Comment by MBilderbeek** [comment] 2020-02-17 20:55
@sdsnatcher I'm sorry to say that it looks like that build is completely wrong. The revision seems to be from a 6 year old commit... I asked @niekniek and he is building a new one. Can you retest with that one please?

**Comment by MBilderbeek** [comment] 2020-02-17 21:41
@sdsnatcher There's a fresh build now, with the latest code...

**Comment by sdsnatcher** [comment] 2020-02-17 22:08
Ok. I downloaded the openmsx-0.15.0-657 revision from there.

This build seems to work a better on fullscreen: the "invisible walls" problem doesn't show up. 

But since it doesn't grab the mouse pointer, whenever I shake the mouse, the macOS own mouse pointer pops up zoomed over the openMSX window. If I manually enable the set grabinput on option this problem doesn't occur.

Note: I have the the "Shake mouse pointer to locate" option enabled under the Control Panel->Accessibility->Display options. AFAICR, this is the default for new Macs.

**Comment by MBilderbeek** [comment] 2020-02-18 19:13
@niekvlessert Can you reproduce this issue?

**Comment by MBilderbeek** [comment] 2020-05-02 20:10
There's currently still the following issue, at least on Linux:
set grabinput on
set fullscreen on
set fullscreen off
and after that, the grabinput isn't working anymore, although it's still 'on'

@niekvlessert @sdsnatcher  @Vampier Can you check whether you also have this issue on macOS or Windows?

**Comment by sdsnatcher** [comment] 2020-05-03 13:27
I tested it on macOS, and the effect was even worse. At the end, the mouse was still grabbed by openMSX, but didn't move the MSX pointer anymore. But I also couldn't use it on the rest of the macOS because it was still grabbed.

If I issued an additional "set grabinbut off" at the end, the problem persisted: the mouse was kept grabbed by openMSX, and yet still didn't work on the MSX Application.


MSX config: Panasonic FS-A1WX running Graph Saurus 2.0 on screen-5.
Tested with openmsx-0.15.0-753 on macOS 10.14.6.

**Comment by MBilderbeek** [comment] 2020-05-03 13:35
@sdsnatcher Which version were you using? And what exactly did you do? (The scenario I posted, I guess?)

**Comment by MBilderbeek** [comment] 2020-05-03 14:12
For me the scenario works fine now using the latest code (wouter committed a possible fix). However, I do notice that when I make very large movements with the mouse, the cursor in the MSX program 'wraps around'. Not sure if that's due to emulation or the actual MSX software.

**Comment by sdsnatcher** [comment] 2020-05-03 14:36
>@sdsnatcher Which version were you using? And what exactly did you do? (The scenario I posted, I guess?)

I tested with the openmsx-0.15.0-753 build on macOS 10.14.6.  I always test with the latest build available on the [openMSX daily builds website](https://openmsx.fixato.net).

>However, I do notice that when I make very large movements with the mouse, the cursor in the MSX program 'wraps around'. Not sure if that's due to emulation or the actual MSX software.

This is a different problem. I reported it on SF back in 2013. It's the bug #892 here on github.

It's a bug where the emulator developers have to decide between usability of being too faithful to the original hardware.

The old MSX mice didn't implement clipping.  But this was understandable, since those mechanical mice had such a low resolution that this problem would hardly show up. The user would have to quickly move the mouse over a kilometer to reproduce this effect in normal working conditions.    😅

But nowadays we have mice and touchpads with a much higher resolution. It's very easy to cause the clipping on everyday use.

WebMSX takes the smartest approach I've seen to the problem, way better than the clipping I proposed on #892 : if the offset is too big to be represented by the MSX mouse, it divides the coordinates transmitted in smaller chunks.

This way not only solves the overflow problem, but it's also able to keep the host pointer in sync with the MSX pointer when running on windowed mode.

**Comment by MBilderbeek** [comment] 2020-05-03 14:40
@sdsnatcher OK, please also try it on the newest build which will appear soon (I guess within about 6 hours).

**Comment by MBilderbeek** [comment] 2020-05-03 14:42
@sdsnatcher In #892 Wouter also wrote that he changed things: "So when an offset is too large it's now send to the MSX in multiple steps (each step clipped to the maximum possible offset)."
That sounds like what you described for WebMSX.

**Comment by sdsnatcher** [comment] 2020-05-03 15:15
Humm. I didn't recall that. 

The overflow you're seeing deserves further investigation then.

**Comment by sdsnatcher** [comment] 2020-05-06 16:43
> @sdsnatcher OK, please also try it on the newest build which will appear soon (I guess within about 6 hours).

Retested it with openMSX-0.15.0-759:

- The grabinput problem is solved. I repeated the steps you detailed, and it worked fine
- I also noticed the overflow problem. It only occurs when the mouse is moved to the right, or to the bottom. When going up or to the left, it never happens.

**Comment by MBilderbeek** [comment] 2020-05-06 18:38
Thanks for testing!

@Vampier Can you also try on Windows, please?

**Comment by MBilderbeek** [comment] 2020-05-09 17:57
(FYI, wrapping issue is further discussed in #892 , see there.)

**Comment by MBilderbeek** [comment] 2020-05-11 19:22
As far as we know, this issue is fixed. @Vampier reported it works fine on Windows as well.

**Closed as completed by MBilderbeek** 2020-05-11 19:22 UTC
Labels: mac
