### ISSUE TITLE
Menu running instance: Scale factor skips values when using cursor keys / Horizontal Stretch not adjustable cursors

### ISSUE THREAD

**Issue by EMLommers** [openMSX/openMSX#1518] opened 2023-06-25 09:30 UTC
When in running instance you change the Video Scale factor and you like to change them by using cursors, 
It goes from 1x to 3x or 4x and skips numbers in the middle.

If you like to change Horizontal Stretch with cursors it is not possible, you have to click space in order to change.

I do not know it this is openMSX or Catapult Issue

**Comment by MBilderbeek** [comment] 2023-06-25 12:24
To be clear: are you making these settings in Catapult and not the OSD menu?
I'm confused, because horizontal stretch is not in Catapult.

**Comment by MBilderbeek** [comment] 2023-06-25 12:48
About the OSD menu: the difference is that settings with numeric values can be changed with cursor keys, but the horizontal stretch is not such a setting. It opens a submenu with the possible values you want to select. 

Do you consider this a high priority issue? If not, I propose to accept the current behaviour.

About the scale factor stuff, isn't that #1169 ?

**Comment by EMLommers** [comment] 2023-06-25 14:18
OSD

Yes! Same as #1169 
It has to do with Scaler option:
simple: jumps from 2 to 4, when selecting 3
hqlite: jumps from 2 to 4,  when selecting 3
RGBTriplet: jumps from 2 to 4,  when selecting 3

No not high priority, but annoying..
Scaler, with cursor keys,
Scale Factor with cursor keys
And all others you can change with cursor keys,
but not Horizontal Stretch...

**Comment by MBilderbeek** [comment] 2023-06-25 15:46
OK, closing as duplicate of #1169.

**Closed as completed by MBilderbeek** 2023-06-25 15:46 UTC
