### ISSUE TITLE
[bug] Function key bindings won't work when the console is open

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1095] opened 2017-12-16 13:25 UTC
New key bindings configured for the function keys won't work when the console is open. An empty square is printed on the console instead.

Steps to reproduce:

1) Add the following new key bindings  on the console:

bind F13 toggle pause
bind F10 toggle console

(note: Depending on your keyboard model, you might have to free the OS-X's own F10 key binding on "Mission Control" settings in the system preferences.)

2) When the console is closed, F10 and F13 will work fine, but once the console is opened they stop working until the console is closed again.

Tested on openMSX 0.14.0-20-gf02f3ce on Mac OS-X 10.11.6.

**Comment by mthuurne** [comment] 2017-12-16 15:39
This works fine for me on Linux, so I guess the problem is specific to macOS.

**Comment by niekvlessert** [comment] 2018-10-06 19:29
Confirmed! I get those little transparant block characters in the console.

I'm on High Sierra.

**Comment by MBilderbeek** [comment] 2018-10-06 19:32
I confirm it doesn't occur on Linux.

**Comment by MBilderbeek** [comment] 2018-10-06 20:00
Apparently on macOS, the console takes precedence over hotkeys....

**Comment by m9710797** [comment] 2018-10-07 07:31
I suspect that on macOS the function key events have a non-zero value in the unicode field. If that's the case the console thinks you're typing text, and that takes priority over hotkey bindings.

I verified that on Linux those events do have value zero in the unicode field. You can check as follows:

- start openMSX from a terminal (so that you can see the stderr output)
- open the openMSX console
- execute:   set kbd_trace_key_presses on
- close the console
- press some function keys

You should then see (on stderr) output like this:

  Key pressed, unicode: 0x0000, keyCode: 0x0011a, keyName: F1
  Key released, unicode: 0x0000, keyCode: 0x40011a, keyName: F1,RELEASE

Notice how these events (for the F1 key) have unicode=0 (for me).

**Comment by niekvlessert** [comment] 2018-10-07 07:39
Tried it. It's interesting; when pressing fn-F11 (that's what it is overhere, normally those keys are for volume and stuff), I get no output on the console, with other keys I do. Maybe OSX is hijacking those key presses. Will look at that later.

**Comment by sdsnatcher** [comment] 2018-10-07 14:32
@m9710797 

This is what I got from the kbd_trace_key_presses on:


Key pressed, unicode: 0xf704, keyCode: 0x0011a, keyName: F1
Key released, unicode: 0x0000, keyCode: 0x40011a, keyName: F1,RELEASE
Key released, unicode: 0x0000, keyCode: 0x400122, keyName: F9,RELEASE
Key released, unicode: 0x0000, keyCode: 0x400124, keyName: F11,RELEASE

Curiously enough, only after I unbound the F11 key its keypresses started showing. Before that, only the release events were printed:
Key pressed, unicode: 0xf70e, keyCode: 0x00124, keyName: F11
Key released, unicode: 0x0000, keyCode: 0x400124, keyName: F11,RELEASE

This happens with the other function keys if I bind them too.

**Comment by sdsnatcher** [comment] 2018-10-07 14:35
Just as a curiosity, I disabled the "Use F1, F2 etc keys as standard function keys" preference on the OSX Keyboard settings, and these were the results with FN+F11 then:

Key pressed, unicode: 0xf70e, keyCode: 0x00124, keyName: F11
Key released, unicode: 0x0000, keyCode: 0x400124, keyName: F11,RELEASE

**Comment by m9710797** [comment] 2018-10-07 17:04
So it's as I expected: function keys on OSX do have a non-zero unicode field, and thus the console will 'eat' those events. And because the font we ship with openMSX does not contain a glyph for e.g. 0xf704 it shows up as an empty square.
It's also normal that bound keys don't show up in the 'kbd_trace_key_presses' output: this is actually a debug feature of the MSX keyboard code. It only shows events that reach the MSX keyboard emulation code, and both the console and the hotkeys (= bound keys) 'eat' events before they can reach the MSX keyboard layer.

**Comment by m9710797** [comment] 2018-10-25 10:31
I did a bit of research: character U+F70E is part of the unicode Private Use Area (PUA). See https://en.wikipedia.org/wiki/Private_Use_Areas

I have no idea why macOS is generating characters in that area. We can easily make openMSX ignore that area, but I'm reluctant to do so because I have no idea what (macOS specific things) it might break. 

OTOH, unless the user switches to a different font, the font we ship with openMSX anyway doesn't contain glyphs for the charcaters in the PUA.

**Comment by sdsnatcher** [comment] 2018-10-25 11:32
Nice finding! And that very same wikipedia article seems to provide the
answer too:


"Apple lists a range of 1,280 characters in its developer documentation[7]
of U+F400–U+F8FF within the PUA for Apple’s use. Of those, only 311 are
used in the range U+F700–U+F8FF (NeXT (NeXTSTEP and OPENSTEP) and Apple
(Mac OS X AppKit)).[8] Of these is U+F8FF the Apple logo generally
supported by Apple's 8-bit sets."



It seems that this Mac OS-X behavior was inherited from NeXTSTEP/OpenStep,
and the article also points to the following documentation that lists the
full list of corporate-zone characters. On the very beginning of that list
are the function keys.


ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT


So, on Mac OS-X, it seems that openMSX will have to deal with the specific corporate-zone chars in order to have the function keys working on any situation.

**Comment by m9710797** [comment] 2018-10-25 16:58
I pushed a fix, but I can't verify myself.
@sdsnatcher: can you test?

**Comment by sdsnatcher** [comment] 2018-10-25 22:20
> @sdsnatcher: can you test?

Yes, with pleasure!

And it works like a charm! Thank you so much for fixing another bug that had been haunting me for quite some time.    :)

**Comment by m9710797** [comment] 2018-10-26 07:03
Closing.

**Closed as completed by m9710797** 2018-10-26 07:03 UTC
